import resolveItems from './util/resolveItems';

const barrows = resolveItems([
	"Ahrim's hood",
	"Ahrim's robetop",
	"Ahrim's robeskirt",
	"Ahrim's staff",
	"Ahrim's armour set",
	"Dharok's helm",
	"Dharok's platebody",
	"Dharok's platelegs",
	"Dharok's greataxe",
	"Dharok's armour set",
	"Guthan's helm",
	"Guthan's platebody",
	"Guthan's chainskirt",
	"Guthan's warspear",
	"Guthan's armour set",
	"Karil's coif",
	"Karil's leathertop",
	"Karil's leatherskirt",
	"Karil's crossbow",
	"Karil's armour set",
	"Torag's helm",
	"Torag's platebody",
	"Torag's platelegs",
	"Torag's hammers",
	"Torag's armour set",
	"Verac's helm",
	"Verac's brassard",
	"Verac's plateskirt",
	"Verac's flail",
	"Verac's armour set",
	'Bolt rack'
]);

const skilling = resolveItems([
	'Rune essence',
	'Copper ore',
	'Tin ore',
	'Iron ore',
	'Silver ore',
	'Pure essence',
	'Coal',
	'Gold ore',
	'Mithril ore',
	'Adamantite ore',
	'Runite ore',
	'Bronze bar',
	'Iron bar',
	'Silver bar',
	'Steel bar',
	'Gold bar',
	'Mithril bar',
	'Adamantite bar',
	'Runite bar',
	'Uncut sapphire',
	'Uncut emerald',
	'Uncut ruby',
	'Uncut diamond',
	'Uncut dragonstone',
	'Uncut onyx',
	'Sapphire',
	'Emerald',
	'Ruby',
	'Diamond',
	'Dragonstone',
	'Onyx',
	'Logs',
	'Oak logs',
	'Willow logs',
	'Teak logs',
	'Maple logs',
	'Bark',
	'Mahogany logs',
	'Yew logs',
	'Mushroom',
	'Magic logs',
	'Redwood logs',
	'Green dragonhide',
	'Blue dragonhide',
	'Red dragonhide',
	'Black dragonhide',
	'Grimy guam leaf',
	'Grimy marrentill',
	'Grimy tarromin',
	'Grimy harralander',
	'Grimy ranarr weed',
	'Grimy irit leaf',
	'Grimy avantoe',
	'Grimy kwuarm',
	'Grimy cadantine',
	'Grimy dwarf weed',
	'Grimy torstol',
	'Grimy lantadyme',
	'Grimy toadflax',
	'Grimy snapdragon',
	'Guam leaf',
	'Marrentill',
	'Tarromin',
	'Harralander',
	'Ranarr weed',
	'Toadflax',
	'Irit leaf',
	'Avantoe',
	'Kwuarm',
	'Snapdragon',
	'Cadantine',
	'Lantadyme',
	'Dwarf weed',
	'Torstol',
	'Ashes',
	'Cactus spine',
	'Crushed nest',
	'Desert goat horn',
	'Limpwurt root',
	'Mort myre fungus',
	'Potato cactus',
	"Red spiders' eggs",
	'Snape grass',
	'White berries',
	"Zulrah's scales",
	'Bones',
	'Dagannoth bones',
	'Dragon bones',
	'Superior dragon bones',
	'Wyvern bones',
	'Plank',
	'Oak plank',
	'Teak plank',
	'Mahogany plank',
	'Guam seed',
	'Marrentill seed',
	'Tarromin seed',
	'Harralander seed',
	'Ranarr seed',
	'Toadflax seed',
	'Irit seed',
	'Avantoe seed',
	'Kwuarm seed',
	'Snapdragon seed',
	'Cadantine seed',
	'Lantadyme seed',
	'Dwarf weed seed',
	'Torstol seed',
	'Willow seed',
	'Maple seed',
	'Yew seed',
	'Magic seed',
	'Palm tree seed',
	'Dragonfruit tree seed',
	'Spirit seed',
	'Celastrus seed',
	'Redwood tree seed',
	'Raw shark',
	'Grapes',
	'Battlestaff',
	'Fire orb',
	'Green dragon leather',
	'Blue dragon leather',
	'Red dragon leather',
	'Black dragon leather'
]);

const gear = resolveItems([
	'Armadyl helmet',
	'Armadyl chestplate',
	'Armadyl chainskirt',
	'Armadyl godsword',
	'Bandos chestplate',
	'Bandos tassets',
	'Bandos boots',
	'Bandos godsword',
	'Saradomin sword',
	'Armadyl crossbow',
	'Saradomin godsword',
	'Zamorakian spear',
	'Staff of the dead',
	'Zamorak godsword',
	'Arcane sigil',
	'Elysian sigil',
	'Spectral sigil',
	'Dragonfire shield',
	'Dragonfire ward',
	"Ahrim's robetop",
	"Ahrim's robeskirt",
	"Ahrim's armour set",
	"Dharok's helm",
	"Dharok's platebody",
	"Dharok's platelegs",
	"Dharok's greataxe",
	"Dharok's armour set",
	"Guthan's armour set",
	"Karil's leathertop",
	"Karil's leatherskirt",
	"Karil's crossbow",
	"Karil's armour set",
	"Torag's armour set",
	"Verac's helm",
	"Verac's brassard",
	"Verac's plateskirt",
	"Verac's flail",
	"Verac's armour set",
	'Anti-dragon shield',
	'Dragon warhammer'
]);

const cluesAndCaskets = resolveItems([
	'Clue scroll (beginner)',
	'Clue scroll (easy)',
	'Clue scroll (medium)',
	'Clue scroll (hard)',
	'Clue scroll (elite)',
	'Clue scroll (master)',
	'Reward casket (beginner)',
	'Reward casket (easy)',
	'Reward casket (medium)',
	'Reward casket (hard)',
	'Reward casket (elite)',
	'Reward casket (master)'
]);

const godwars = resolveItems([
	'Bandos tassets',
	'Bandos chestplate',
	'Bandos boots',
	'Bandos hilt',
	'Bandos godsword',
	'Pet general graardor',
	'Armadyl helmet',
	'Armadyl chestplate',
	'Armadyl chainskirt',
	'Armadyl hilt',
	'Armadyl godsword',
	"Pet kree'arra",
	'Zamorakian spear',
	'Zamorak hilt',
	'Zamorak godsword',
	'Staff of the dead',
	'Steam battlestaff',
	"Pet k'ril tsutsaroth",
	'Saradomin sword',
	"Saradomin's light",
	'Armadyl crossbow',
	'Saradomin hilt',
	'Saradomin godsword',
	'Pet zilyana',
	'Godsword shard 1',
	'Godsword shard 2',
	'Godsword shard 3',
	'Godsword blade'
]);

const dagannothkings = resolveItems([
	'Berserker ring',
	'Warrior ring',
	'Archers ring',
	'Seers ring',
	'Dragon axe',
	'Fremennik helm',
	'Fremennik blade',
	'Fremennik shield',
	'Rock-shell helm',
	'Rock-shell plate',
	'Rock-shell legs',
	'Rock-shell boots',
	'Rock-shell gloves',
	'Berserker helm',
	'Warrior helm',
	'Pet dagannoth rex',
	'Seercull',
	'Spined helm',
	'Spined body',
	'Spined chaps',
	'Spined boots',
	'Spined gloves',
	'Archer helm',
	'Pet dagannoth supreme',
	'Skeletal helm',
	'Skeletal top',
	'Skeletal bottoms',
	'Skeletal boots',
	'Skeletal gloves',
	'Mud battlestaff',
	'Pet dagannoth prime'
]);

const cerberus = resolveItems([
	'Primordial crystal',
	'Pegasian crystal',
	'Eternal crystal',
	'Smouldering stone',
	'Key master teleport',
	'Jar of souls',
	'Hellpuppy'
]);

const zulrah = resolveItems([
	"Zulrah's scales",
	'Tanzanite mutagen',
	'Magma mutagen',
	'Tanzanite fang',
	'Magic fang',
	'Serpentine visage',
	'Uncut onyx',
	'Zul-andra teleport',
	'Jar of swamp',
	'Pet snakeling',
	'Tanzanite helm',
	'Magma helm',
	'Toxic blowpipe',
	'Uncharged toxic trident',
	'Trident of the swamp',
	'Serpentine helm'
]);

const corporealbeast = resolveItems([
	'Spectral sigil',
	'Arcane sigil',
	'Elysian sigil',
	'Spirit shield',
	'Holy elixir',
	'Pet dark core',
	'Onyx bolts (e)',
	'Blessed spirit shield',
	'Spectral spirit shield',
	'Arcane spirit shield',
	'Elysian spirit shield'
]);

const kalphitequeen = resolveItems([
	'Dragon chainbody',
	'Dragon 2h sword',
	'Kq head',
	'Jar of sand',
	'Kalphite princess'
]);

export const filterableTypes = [
	{
		name: 'Barrows',
		aliases: ['barrows', 'br'],
		items: barrows
	},
	{
		name: 'Skilling',
		aliases: ['skilling', 'skill'],
		items: skilling
	},
	{
		name: 'Gear',
		aliases: ['gear', 'gr'],
		items: gear
	},
	{
		name: 'Clues and Caskets',
		aliases: ['clues', 'caskets', 'cl', 'clue', 'casket', 'tt'],
		items: cluesAndCaskets
	},
	{
		name: 'God wars',
		aliases: ['gwd', 'godwars', 'gw'],
		items: godwars
	},
	{
		name: 'Dagannoth kings',
		aliases: ['dks', 'dk', 'dagannoth', 'kings'],
		items: dagannothkings
	},
	{
		name: 'Cerberus',
		aliases: ['cerb', 'ce'],
		items: cerberus
	},
	{
		name: 'Zulrah',
		aliases: ['zul', 'zulr'],
		items: zulrah
	},
	{
		name: 'Corporeal beast',
		aliases: ['corp', 'co', 'corporeal'],
		items: corporealbeast
	},
	{
		name: 'Kalphite queen',
		aliases: ['kq', 'ka', 'kalphite', 'queen'],
		items: kalphitequeen
	}
];
