import { transformArrayOfResolvableItems } from './util/transformArrayOfResolvableItems';

const barrows = transformArrayOfResolvableItems([
	"Ahrim's hood",
	"Ahrim's robetop",
	"Ahrim's robeskirt",
	"Ahrim's staff",
	"Ahrim's armour set",
	"Dharok's helm",
	"Dharok's platebody",
	"Dharok's platelegs",
	"Dharok's greataxe",
	"Dharok's armour set",
	"Guthan's helm",
	"Guthan's platebody",
	"Guthan's chainskirt",
	"Guthan's warspear",
	"Guthan's armour set",
	"Karil's coif",
	"Karil's leathertop",
	"Karil's leatherskirt",
	"Karil's crossbow",
	"Karil's armour set",
	"Torag's helm",
	"Torag's platebody",
	"Torag's platelegs",
	"Torag's hammers",
	"Torag's armour set",
	"Verac's helm",
	"Verac's brassard",
	"Verac's plateskirt",
	"Verac's flail",
	"Verac's armour set",
	'Bolt rack'
]);

const skilling = transformArrayOfResolvableItems([
	'Rune essence',
	'Copper ore',
	'Tin ore',
	'Iron ore',
	'Silver ore',
	'Pure essence',
	'Coal',
	'Gold ore',
	'Mithril ore',
	'Adamantite ore',
	'Runite ore',
	'Bronze bar',
	'Iron bar',
	'Silver bar',
	'Steel bar',
	'Gold bar',
	'Mithril bar',
	'Adamantite bar',
	'Runite bar',
	'Uncut sapphire',
	'Uncut emerald',
	'Uncut ruby',
	'Uncut diamond',
	'Uncut dragonstone',
	'Uncut onyx',
	'Logs',
	'Oak logs',
	'Willow logs',
	'Teak logs',
	'Maple logs',
	'Bark',
	'Mahogany logs',
	'Yew logs',
	'Mushroom',
	'Magic logs',
	'Redwood logs',
	'Green dragonhide',
	'Blue dragonhide',
	'Red dragonhide',
	'Black dragonhide',
	'Grimy guam leaf',
	'Grimy marrentill',
	'Grimy tarromin',
	'Grimy harralander',
	'Grimy ranarr weed',
	'Grimy irit leaf',
	'Grimy avantoe',
	'Grimy kwuarm',
	'Grimy cadantine',
	'Grimy dwarf weed',
	'Grimy torstol',
	'Grimy lantadyme',
	'Grimy toadflax',
	'Grimy snapdragon',
	'Guam leaf',
	'Marrentill',
	'Tarromin',
	'Harralander',
	'Ranarr weed',
	'Toadflax',
	'Irit leaf',
	'Avantoe',
	'Kwuarm',
	'Snapdragon',
	'Cadantine',
	'Lantadyme',
	'Dwarf weed',
	'Torstol',
	'Ashes',
	'Cactus spine',
	'Crushed nest',
	'Desert goat horn',
	'Limpwurt root',
	'Mort myre fungus',
	'Potato cactus',
	"Red spiders' eggs",
	'Snape grass',
	'White berries',
	"Zulrah's scales",
	'Bones',
	'Dagannoth bones',
	'Dragon bones',
	'Superior dragon bones',
	'Wyvern bones',
	'Plank',
	'Oak plank',
	'Teak plank',
	'Mahogany plank',
	'Guam seed',
	'Marrentill seed',
	'Tarromin seed',
	'Harralander seed',
	'Ranarr seed',
	'Toadflax seed',
	'Irit seed',
	'Avantoe seed',
	'Kwuarm seed',
	'Snapdragon seed',
	'Cadantine seed',
	'Lantadyme seed',
	'Dwarf weed seed',
	'Torstol seed',
	'Willow seed',
	'Maple seed',
	'Yew seed',
	'Magic seed',
	'Palm tree seed',
	'Dragonfruit tree seed',
	'Spirit seed',
	'Celastrus seed',
	'Redwood tree seed',
	'Raw shark',
	'Grapes'
]);

const gear = transformArrayOfResolvableItems([
	'Armadyl helmet',
	'Armadyl chestplate',
	'Armadyl chainskirt',
	'Armadyl godsword',
	'Bandos chestplate',
	'Bandos tassets',
	'Bandos boots',
	'Bandos godsword',
	'Saradomin sword',
	'Armadyl crossbow',
	'Saradomin godsword',
	'Zamorakian spear',
	'Staff of the dead',
	'Zamorak godsword',
	'Arcane sigil',
	'Elysian sigil',
	'Spectral sigil',
	'Dragonfire shield',
	'Dragonfire ward',
	"Ahrim's robetop",
	"Ahrim's robeskirt",
	"Ahrim's armour set",
	"Dharok's helm",
	"Dharok's platebody",
	"Dharok's platelegs",
	"Dharok's greataxe",
	"Dharok's armour set",
	"Guthan's armour set",
	"Karil's leathertop",
	"Karil's leatherskirt",
	"Karil's crossbow",
	"Karil's armour set",
	"Torag's armour set",
	"Verac's helm",
	"Verac's brassard",
	"Verac's plateskirt",
	"Verac's flail",
	"Verac's armour set",
	'Anti-dragon shield'
]);

const cluesAndCaskets = transformArrayOfResolvableItems([
	'Clue scroll (beginner)',
	'Clue scroll (easy)',
	'Clue scroll (medium)',
	'Clue scroll (hard)',
	'Clue scroll (elite)',
	'Clue scroll (master)',
	'Reward casket (beginner)',
	'Reward casket (easy)',
	'Reward casket (medium)',
	'Reward casket (hard)',
	'Reward casket (elite)',
	'Reward casket (master)'
]);

export const filterableTypes = [
	{
		name: 'Barrows',
		aliases: ['barrows', 'br'],
		items: barrows
	},
	{
		name: 'Skilling',
		aliases: ['skilling', 'skill'],
		items: skilling
	},
	{
		name: 'Gear',
		aliases: ['gear', 'gr'],
		items: gear
	},
	{
		name: 'Clues and Caskets',
		aliases: ['clues', 'caskets', 'cl', 'clue', 'casket', 'tt'],
		items: cluesAndCaskets
	}
];
