import { LootTable } from 'oldschooljs';

const BronzeChestRed = new LootTable({ limit: 99 })
	.every('Swamp paste', [10, 20])
	.tertiary(63, 'Bronze locks')
	.tertiary(4, 'Coins', [1, 270])
	.oneIn(3000, 'Steel longsword')
	.oneIn(3000, 'Black spear')
	.add('Steel axe', 1, 6)
	.add('Magic staff', 1, 6)
	.add('Black dagger', 1, 6)
	.add('Black dagger(p)', 1, 5)
	.add('Mithril dagger', 1, 5)
	.add('Mithril dagger(p)', 1, 4)
	.add('Steel spear', 1, 4)
	.add('Steel spear(p)', 1, 4)
	.add('Steel sword', 1, 4)
	.add('Steel mace', 1, 3)
	.add('Steel scimitar', 1, 3)
	.add('Black mace', 1, 2)
	.add('Black axe', 1, 1)
	.add('Chaos rune', [12, 29], 14)
	.add('Amulet of defence', 1, 7)
	.add('Silver bar', 3, 6)
	.add('Steel med helm', 1, 5)
	.add('Gold bar', 3, 5)
	.add('Mithril bar', 3, 5)
	.add('Clue scroll (easy)', 1, 2)
	.add('Sapphire ring', 1, 2);
