packages:
  - packages/*
  - docs
  - "!**/packages/test-dashboard"

ignoredBuiltDependencies:
  - wtf_wikipedia

neverBuiltDependencies: []

overrides:
  "sharp": "0.34.4"
  "dotenv": "16.5.0"
  "tsdown>rolldown": "1.0.0-beta.47"
  "discord-api-types": "0.38.32"
  "undici-types": "7.14.0"
  "@types/node": "24.5.2"
  "esbuild": "0.25.11"
  "emoji-regex": "10.6.0"
