packages:
  - packages/*
  - docs
  - "!**/packages/test-dashboard"

ignoredBuiltDependencies:
  - wtf_wikipedia

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - bufferutil
  - esbuild
  - prisma
  - sharp
  - skia-canvas
