import { EItem } from '../EItem';

export const toaCL = [
	EItem.TUMEKENS_GUARDIAN,
	EItem.TUMEKENS_SHADOW_UNCHARGED,
	EItem.ELIDINIS_WARD,
	EItem.MASORI_MASK,
	EItem.MASORI_BODY,
	EItem.MASORI_CHAPS,
	EItem.LIGHTBEARER,
	EItem.OSMUMTENS_FANG,
	EItem.THREAD_OF_ELIDINIS,
	EItem.BREACH_OF_THE_SCARAB,
	EItem.EYE_OF_THE_CORRUPTOR,
	EItem.JEWEL_OF_THE_SUN,
	EItem.MENAPHITE_ORNAMENT_KIT,
	EItem.CURSED_PHALANX,
	EItem.MASORI_CRAFTING_KIT,
	EItem.CACHE_OF_RUNES,
	EItem.ICTHLARINS_SHROUD_TIER_1,
	EItem.ICTHLARINS_SHROUD_TIER_2,
	EItem.ICTHLARINS_SHROUD_TIER_3,
	EItem.ICTHLARINS_SHROUD_TIER_4,
	EItem.ICTHLARINS_SHROUD_TIER_5,
	EItem.REMNANT_OF_AKKHA,
	EItem.REMNANT_OF_BABA,
	EItem.REMNANT_OF_KEPHRI,
	EItem.REMNANT_OF_ZEBAK,
	EItem.ANCIENT_REMNANT
];

export const toaPurpleItems = [
	EItem.TUMEKENS_GUARDIAN,
	EItem.TUMEKENS_SHADOW_UNCHARGED,
	EItem.ELIDINIS_WARD,
	EItem.MASORI_MASK,
	EItem.MASORI_BODY,
	EItem.MASORI_CHAPS,
	EItem.LIGHTBEARER,
	EItem.OSMUMTENS_FANG
];

export const godWarsDungeonGodswordShards = [EItem.GODSWORD_SHARD_1, EItem.GODSWORD_SHARD_2, EItem.GODSWORD_SHARD_3];
