import { Bank } from 'oldschooljs';

import itemID from '../../../util/itemID';
import type { Plant } from '../../types';

const hopsPlants: Plant[] = [
	{
		id: itemID('Barley'),
		level: 3,
		plantXp: 8.5,
		checkXp: 0,
		harvestXp: 9.5,
		inputItems: new Bank({ 'Barley seed': 4 }).freeze(),
		outputCrop: itemID('Barley'),
		name: 'Barley',
		aliases: ['barley'],
		petChance: 112_416,
		seedType: 'hops',
		growthTime: 40,
		numOfStages: 4,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ Compost: 3 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Hammerstone hops'),
		level: 4,
		plantXp: 9,
		checkXp: 0,
		harvestXp: 10,
		inputItems: new Bank({ 'Hammerstone seed': 4 }).freeze(),
		outputCrop: itemID('Hammerstone hops'),
		name: 'Hammerstone hops',
		aliases: ['hammerstone hops', 'hammerstone', 'hammer'],
		petChance: 112_416,
		seedType: 'hops',
		growthTime: 40,
		numOfStages: 4,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ Marigolds: 1 }),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Asgarnian hops'),
		level: 8,
		plantXp: 10.9,
		checkXp: 0,
		harvestXp: 12,
		inputItems: new Bank({ 'Asgarnian seed': 4 }).freeze(),
		outputCrop: itemID('Asgarnian hops'),
		name: 'Asgarnian hops',
		aliases: ['asgarnian hops', 'asgarnian', 'asgar'],
		petChance: 112_416,
		seedType: 'hops',
		growthTime: 50,
		numOfStages: 5,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ 'Onions(10)': 1 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Jute fibre'),
		level: 13,
		plantXp: 13,
		checkXp: 0,
		harvestXp: 14.5,
		inputItems: new Bank({ 'Jute seed': 3 }).freeze(),
		outputCrop: itemID('Jute fibre'),
		name: 'Jute',
		aliases: ['jute', 'jute fibre'],
		petChance: 89_933,
		seedType: 'hops',
		growthTime: 50,
		numOfStages: 5,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ 'Barley malt': 6 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Yanillian hops'),
		level: 16,
		plantXp: 14.5,
		checkXp: 0,
		harvestXp: 16,
		inputItems: new Bank({ 'Yanillian seed': 4 }).freeze(),
		outputCrop: itemID('Yanillian hops'),
		name: 'Yanillian hops',
		aliases: ['yanillian hops', 'yanillian', 'yan'],
		petChance: 74_944,
		seedType: 'hops',
		growthTime: 40,
		numOfStages: 4,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ 'Tomatoes(5)': 200 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Krandorian hops'),
		level: 21,
		plantXp: 17.5,
		checkXp: 0,
		harvestXp: 19.5,
		inputItems: new Bank({ 'Krandorian seed': 4 }).freeze(),
		outputCrop: itemID('Krandorian hops'),
		name: 'Krandorian hops',
		aliases: ['krandorian hops', 'krandorian', 'kran'],
		petChance: 64_238,
		seedType: 'hops',
		growthTime: 40,
		numOfStages: 4,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ 'Cabbages(10)': 3 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	},
	{
		id: itemID('Wildblood hops'),
		level: 28,
		plantXp: 23,
		checkXp: 0,
		harvestXp: 26,
		inputItems: new Bank({ 'Wildblood seed': 4 }).freeze(),
		outputCrop: itemID('Wildblood hops'),
		name: 'Wildblood hops',
		aliases: ['wildblood hops', 'wildblood', 'wild'],
		petChance: 56_208,
		seedType: 'hops',
		growthTime: 40,
		numOfStages: 4,
		chance1: 154,
		chance99: 183,
		chanceOfDeath: 25,
		protectionPayment: new Bank({ Nasturtiums: 1 }).freeze(),
		needsChopForHarvest: false,
		fixedOutput: false,
		givesLogs: false,
		givesCrops: true,
		defaultNumOfPatches: 4,
		canPayFarmer: true,
		canCompostPatch: true,
		canCompostandPay: true,
		// [QP, Patches Gained]
		additionalPatchesByQP: [],
		// [Farm Lvl, Patches Gained]
		additionalPatchesByFarmLvl: [],
		additionalPatchesByFarmGuildAndLvl: [],
		timePerPatchTravel: 20,
		timePerHarvest: 20
	}
];

export default hopsPlants;
