import { readFileSync, writeFileSync } from 'node:fs';

export function handleMarkdownEmbed(identifier: string, filePath: string, contentToInject: string) {
	const contentToReplace = readFileSync(`./docs/src/content/docs/${filePath}`, 'utf8');
	const startMarker = `[[embed.${identifier}.start]]`;
	const endMarker = `[[embed.${identifier}.end]]`;
	const startIndex = contentToReplace.indexOf(startMarker);
	const endIndex = contentToReplace.indexOf(endMarker);

	if (startIndex === -1 || endIndex === -1) {
		console.error(`Markers (not found in the file. ${filePath} ${identifier}`);
		process.exit(1);
	}

	const autoComment = '{/* DO NOT EDIT - This section is auto-generated by the build script */}';
	const newContent = `${contentToReplace.slice(0, startIndex + startMarker.length)}
${autoComment}
${contentToInject}
${autoComment}
${contentToReplace.slice(endIndex)}`;

	writeFileSync(`./docs/src/content/docs/${filePath}`, newContent, 'utf8');
}
