import { KlasaUser } from 'klasa';

export default class LastManStandingUsage {
	public contestants = 0;
	public deaths: Set<number> = new Set();
	public killers: Set<number> = new Set();
	private readonly parts: (string | number)[] = [];

	public constructor(usage: string) {
		this.parse(usage);
	}

	public display(...values: KlasaUser[]) {
		return this.parts
			.map(part => (typeof part === 'number' ? values[part].username : part))
			.join('');
	}

	public parse(usage: string): void {
		let current = '';
		for (let i = 0, char; i < usage.length; i++) {
			char = usage.charAt(i);
			if (char === '{') {
				// If there was text, push buffer
				if (current) {
					this.parts.push(current);
					current = '';
				}

				// Parse tag {NT?}
				const n = Number(usage.charAt(++i));

				// If N > contestants, assign contestants to N
				if (n > this.contestants) this.contestants = n;

				const nextChar = ++i;
				// If D, add death; if K, add killer
				if (usage.charAt(nextChar) === 'D') {
					this.deaths.add(n - 1);
					i++;
				} else if (usage.charAt(nextChar) === 'K') {
					this.killers.add(n - 1);
					i++;
				}

				this.parts.push(n - 1);
			} else {
				current += char;
			}
		}

		if (current) this.parts.push(current);
	}
}

export const LMS_BLOODBATH = [
	'{1} grabs a DDS.',
	'{1} grabs an Abyssal whip and retreats.',
	'{1} and {2} fight for a whip. {1} gives up and retreats.',
	'{1} and {2} fight for a whip. {2} gives up and retreats.',
	"{1} finds a Heavy ballista, some Javelins, and an Ava's assembler.",
	'{1} runs into upstairs in a building and hides.',
	'{1} takes a handful of Morrigan Javelins.',
	"{1} rips a Zuriel's staff out of {2}'s hands.",
	'{1} finds a vial full of Saradomin brew.',
	'{1} Loots a death pile for resources.',
	'{1} gathers as much food as they can.',
	'{1} grabs a Vesta longsword.',
	'{1} takes a Gharazi Rapier from inside the Trinity Outpost.',
	'{1} finds a Crate with an Infernal cape.',
	'{1} clutches a Bloody key and runs away.',
	'{1} takes a AGS from inside the Moser Settlement.',
	'{1}, {2}, and {3} work together to get as many supplies as possible.',
	'{1} runs away with a pair of Eternal boots and some sharks.',
	'{1} snatches a vial of Super restore and a Stamina potion.',
	'{1} finds a supply box full of Granite mauls & supplies.',
	'{1} searches a supply box, not realizing it is empty.',
	'{1} DDS specs {2} for a single Karambwan.',
	'{1}, {2}, {3}, and {4} share everything they gathered before running.',
	'{1} retrieves a Staff of the Dead from the Debtor hideout .',
	"{1} grabs a Stamina potion while {2} gets Ahrim's robes.",
	'{1} scares {2} away from the Moser Settlement.',
	'{1} grabs a Dragonfire shield from the ground on The Mountain.',
	'{1} snatches a pair of Dragon claws.',
	'{1} grabs a lone pair of pants.',
	'{1D} steps out of the safezone too soon and gets killed by the fog.',
	"{1K} throws a Morrigan Javelin into {2D}'s head.",
	'{1D} gets 6 Hour logged and dies.',
	'{1K} catches {2D} off guard and AGS specs a 73.',
	'{1K} and {2K} work together to drown {3D}.',
	'{1K} smites {2D} and kills them after engaging in a fist fight.',
	"{1K} shoots a Dragon arrow into {2D}'s head.",
	'{1D} cannot handle the circumstances and runs in the fog.',
	"{1K} bashes {2D}'s head against a Granite maul several times.",
	"{1K} snaps {2D}'s neck with their bare hands.",
	'{1K} decapitates {2D} with a Ghrazi Rapier.',
	"{1K} plunges a Dragon dagger in {2D}'s abdomen.",
	'{1K} sets {2D} on fire with an Infernal cape.',
	'{1D} falls into a pit and dies.',
	'{1K} stabs {2D} while their back is turned.',
	'{1K} severely injures {2D}, but puts them out of their misery.',
	'{1K} severely injures {2D} and leaves them to die.',
	"{1K} bashes {2D}'s head in with an Elder maul.",
	'{1K} pushes {2D} off a cliff during a whip fight.',
	"{1K} throws a Dragon knife into {2D}'s chest.",
	'{1D} is unable to convince {2K} to not kill them.',
	'{1K} convinces {2D} to not kill them, only to kill {2D} instead.',
	'{1D} falls into the River and drowns.',
	'{1K}, {2}, and {3D} start fighting, but {2} runs away as {1K} kills {3D}.',
	'{1K} kills {2D} with their own spec weapon.',
	'{1K} overpowers {2D}, killing them.',
	'{1K} throws a Chinchompa, killing {2D}.',
	'{1K} throws a Chinchompa, killing {2D}, and {3D}.',
	'{1K} throws a Chinchompa, killing {2D}, {3D}, and {4D}.',
	'{1K} throws a Chinchompa, killing {2D}, {3D}, {4D} and {5D}.',
	'{1K} kills {2D} as they try to run.',
	'{1D} and {2D} threaten a double suicide. It fails and they die.',
	'{1D}, {2D}, {3D}, and {4D} form a suicide pact, and run in the fog.',
	'{1K} kills {2D} with a Dragon thrownaxe.',
	'{1K} and {2K} fight {3D} and {4D}. {1K} and {2K} survive.',
	'{1D} and {2D} fight {3K} and {4K}. {3K} and {4K} survive.',
	'{1D} attacks {2}, but {3K} protects them, killing {1D}.',
	'{1K} severely slices {2D} with an Armadyl godsword.',
	'{1K} strangles {2D} with an Abyssal whip.',
	'{1K} kills {2D} for their supplies.',
	'{1K} hurls a Dragon Javelin at {2}, but misses and kills {3D} instead.',
	"{1K} shoots a poisonous Dragon dart into {2D}'s neck, slowly killing them.",
	'{1K} stabs {2D} with a Ghrazi rapier.',
	'{1K} stabs {2D} in the back with a Zuriels Staff.',
	'{1K}, {2D}, and {3D} get into a fight. {1K} triumphantly kills them both.',
	'{1D}, {2K}, and {3D} get into a fight. {2K} triumphantly kills them both.',
	'{1D}, {2D}, and {3K} get into a fight. {3K} triumphantly kills them both.',
	'{1K} finds {2D} hiding in the Debtor Hideout and kills them.',
	'{1D} finds {2K} hiding in the Debtor Hideout, but {2K} kills them.',
	'{1K} kills {2D} with a Dragon scimitar.',
	'{1K} and {2D} fight for a crate.{1K} strangles {2D} with a whip and runs.',
	'{1D} and {2K} fight for a crate.{2K} strangles {1D} with a whip and runs.',
	'{1K} repeatedly stabs {2D} to death with a Ghrazi Rapier.',
	'{1D} trips over while running from the fog, and is killed by {2K}.',
	'{1} trips over while running from the fog, {2} picks them up, they run off together.',
	"{1K} aims a Dragon arrow at {2}'s head and shoots, {3D} jumps in the way and sacrifices their life to save them."
].map(string => new LastManStandingUsage(string));

export const LMS_DAY = [
	'{1} goes hunting.',
	'{1} injures themself.',
	'{1} explores the arena.',
	'{1} scares {2} off.',
	"{1} diverts {2}'s attention and runs away.",
	'{1} stalks {2}.',
	'{1} eats a shark.',
	'{1} camouflauges themself in the bushes.',
	"{1} pickpockets {2} while they aren't looking.",
	'{1} finds a dragon spear.',
	'{1} discovers a cave.',
	'{1} attacks {2}, but they manage to escape.',
	'{1} chases {2}.',
	'{1} runs away from {2}.',
	'{1} receives a Twisted bow from an unknown sponsor.',
	'{1} receives a super combat potion from an unknown sponsor.',
	'{1} receives a bag of potions from an unknown sponsor.',
	'{1} receives fresh food from an unknown sponsor.',
	'{1} defeats {2} in a fight, but spares their life.',
	'{1} and {2} work together for now.',
	'{1} begs for {2} to kill them. They refuse, keeping {1} alive.',
	'{1} tries to stay hidden for the entire day.',
	"{1}, {2}, {3}, and {4} raid {5}'s chest while they are looting.",
	'{1} overhears {2} and {3} talking in the distance.',
	'{1} practices their archery.',
	'{1} thinks about home.',
	'{1} is pricked by thorns while picking cavada berries.',
	'{1} tries to spear fish with a trident.',
	'{1} searches for firewood.',
	'{1} and {2} split up to search for supplies.',
	'{1} picks flowers.',
	"{1} tends to {2}'s wounds.",
	'{1} sees smoke rising in the distance, but decides not to investigate.',
	'{1} sprains their ankle while running away from {2}.',
	'{1} makes a crossbow.',
	'{1} travels to higher ground.',
	'{1} discovers a river.',
	'{1} hunts for other contestants.',
	'{1} and {2} hunt for other contestants.',
	'{1}, {2}, and {3} hunt for other contestants.',
	'{1}, {2}, {3}, and {4} hunt for other contestants.',
	'{1}, {2}, {3}, {4}, and {5} hunt for other contestants.',
	'{1} receives a bag of chinchompas from an unknown sponsor.',
	'{1} questions their sanity.',
	'{1} forces {2} to eat pant.',
	'{1K} forces {2D} to eat pant. {2D} chokes and dies.',
	'{1K} catches {2D} off guard and kills them.',
	"{1K} throws a dragon knife into {2D}'s head.",
	'{1D} begs for {2K} to kill them. They reluctantly oblige, killing {1D}.',
	'{1K} and {2K} work together to spec out {3D}.',
	'{1K} strangles {2D} after engaging in a risk fight.',
	"{1K} shoots an arrow into {2D}'s head.",
	'{1D} bleeds out due to untreated injuries.',
	'{1D} cannot handle the circumstances and logs out.',
	"{1K} bashes {2D}'s head against a rock several times.",
	'{1D} unknowingly eats cavada berries.',
	"{1K} silently snaps {2D}'s neck.",
	"{1K} taints {2D}'s food, killing them.",
	'{1K} decapitates {2D} with an AGS spec.',
	'{1D} dies from an infection.',
	'{1K} spears {2D} in the abdomen.',
	'{1K} sets {2D} on fire with Flames of Zamorak.',
	'{1D} falls into a pit and dies.',
	"{1K} DDS specs {2D} while they're purchasing supplies.",
	'{1K} severely injures {2D}, but puts them out of their misery.',
	'{1K} severely injures {2D} and leaves them to die.',
	"{1K} bashes {2D}'s head in with a Dragon mace.",
	'{1D} attempts to climb a tree, but falls to their death.',
	'{1K} pushes {2D} off a cliff during a knife fight.',
	"{1K} throws a dragon knife into {2D}'s chest.",
	"{1K}'s trap kills {2D}.",
	'{1K} kills {2D} while they are resting.',
	'{1D} is unable to convince {2K} to not kill them.',
	'{1K} convinces {2D} to not kill them, only to kill {2D} instead.',
	'{1D} unknowingly runs into the fog and dies.',
	'{1K}, {2}, and {3D} start fighting, but {2} runs away as {1K} kills {3D}.',
	'{1K} kills {2D} with their own weapon.',
	'{1K} overpowers {2D}, killing them.',
	'{1K} throws a chinchompa, killing {2D}.',
	'{1K} throws a chinchompa, killing {2D}, and {3D}.',
	'{1K} throws a chinchompa, killing {2D}, {3D}, and {4D}.',
	'{1K} throws a chinchompa, killing {2D}, {3D}, {4D} and {5D}.',
	'{1K} kills {2D} as they try to run.',
	'{1D} and {2D} threaten a double suicide. It fails and they die.',
	'{1D}, {2D}, {3D}, and {4D} form a suicide pact, killing themselves.',
	'{1D} dies from poison.',
	'{1D} dies from venom.',
	'{1D} dies from disease.',
	"{1K} kills {2D} with a Morrigan's throwing axe.",
	'{1K} and {2K} fight {3D} and {4D}. {1K} and {2K} survive.',
	'{1D} and {2D} fight {3K} and {4K}. {3K} and {4K} survive.',
	'{1D} dies in the fog trying to escape the arena.',
	'{1D} accidently detonates a chinchompa trying to throw it.',
	'{1D} attacks {2}, but {3K} protects them, killing {1D}.',
	'{1K} ambushes {2D} and kills them.',
	'{1D} accidently steps on a trap.',
	'{1K} severely slices {2D} with an AGS spec.',
	'{1K} strangles {2D} with an Abyssal whip.',
	'{1K} kills {2D} for their supplies.',
	'{1K} shoots an arrow at {2}, but misses and kills {3D} instead.',
	"{1K} shoots a poisonous blow dart into {2D}'s neck, slowly killing them.",
	'{1K}, {2K}, and {3K} successfully ambush and kill {4D}, {5D}, and {6D}.',
	'{1D}, {2D}, and {3D} unsuccessfully ambush {4K}, {5K}, and {6K}, who kill them instead.',
	'{1K} shoots {2D} with a Dark bow.',
	'{1} forces {2K} to kill {3D} or {4}. They decide to kill {3D}.',
	'{1} forces {2K} to kill {3} or {4D}. They decide to kill {4D}.',
	'{1K} forces {2D} to kill {3} or {4}. They refuse to kill, so {1K} kills them instead.',
	"{1D} poisons {2}'s potion, but mistakes it for their own and dies.",
	"{1K} poisons {2D}'s potion. They drink it and die.",
	"{1K} stabs {2D} in the back with a Vesta's longsword.",
	'{1D} attempts to climb a tree, but falls on {2D}, killing them both.',
	'{1K}, {2D}, and {3D} get into a fight. {1K} triumphantly kills them both.',
	'{1D}, {2K}, and {3D} get into a fight. {2K} triumphantly kills them both.',
	'{1D}, {2D}, and {3K} get into a fight. {3K} triumphantly kills them both.',
	'{1K} kills {2D} with a Ghrazi rapier.',
	'{1K}, {2K}, {3K}, {4K}, and {5K} track down and kill {6D}.',
	'{1K}, {2K}, {3K}, and {4K} track down and kill {5D}.',
	'{1K}, {2K}, and {3K} track down and kill {4D}.',
	'{1K} and {2K} track down and kill {3D}.',
	'{1K} tracks down and kills {2D}.',
	'{1K} repeatedly stabs {2D} to death with Draggon dagger.',
	'{1} doodles in the dirt.',
	'{1} chases a butterfly.',
	'{1D} falls off a cliff, and is impaled by a stick.',
	'{1} runs into {2}, they decide to team up.',
	'{1} sees {2} through the trees, and plans on killing them.',
	'{1K} sneaks up behind {2D}, and barrages them.',
	'{1D} challenges {2K} to a fight, and promptly dies.',
	'{1K} murders their partner, {2D}, to have more supplies for themself.'
].map(string => new LastManStandingUsage(string));

export const LMS_NIGHT = [
	'{1} starts a fire.',
	'{1} searches for a bloody chest.',
	'{1} loses sight of where they are.',
	'{1} hides in a building to rest.',
	'{1} eats all their food.',
	'{1} and {2} tell stories about themselves to each other.',
	'{1} tends to their wounds.',
	'{1} sees a fire, but stays hidden.',
	'{1} screams for help.',
	'{1} stays awake all night.',
	'{1} passes out from exhaustion.',
	'{1} cooks their food before putting their fire out.',
	'{1} and {2} run into each other and decide to truce for the night.',
	'{1} fends {2}, {3}, and {4} away from their fire.',
	'{1}, {2}, and {3} discuss the games and what might happen in the morning.',
	'{1} cries themself to sleep.',
	'{1} tries to treat their infection.',
	'{1} and {2} talk about the contestants still alive.',
	'{1} is awoken by nightmares.',
	'{1} and {2} huddle for warmth.',
	'{1} thinks about winning.',
	'{1}, {2}, {3}, and {4} tell each other ghost stories to lighten the mood.',
	'{1} looks at the night sky.',
	'{1} defeats {2} in a fight, but spares their life.',
	'{1} begs for {2} to kill them. They refuse, keeping {1} alive.',
	"{1} destroys {2}'s supplies while they are asleep.",
	'{1} lets {2} into their shelter.',
	'{1} receives a Dragon hatchet from an unknown sponsor.',
	'{1} receives a combat potion from an unknown sponsor.',
	'{1} receives a bag of potions from an unknown sponsor.',
	'{1} receives food from an unknown sponsor.',
	'{1} attempts to start a fire, but is unsuccessful.',
	'{1} thinks about home.',
	"{1} tends to {2}'s wounds.",
	'{1} quietly hums.',
	'{1}, {2}, and {3} cheerfully sing songs together.',
	'{1} and {2} hold hands.',
	'{1} convinces {2} to snuggle with them.',
	'{1} receives a chinchompa from an unknown sponsor.',
	'{1} questions their sanity.',
	'{1} forces {2} to eat pant.',
	'{1K} forces {2D} to eat pant. {2D} chokes and dies.',
	'{1K} catches {2D} off guard and kills them.',
	"{1K} throws a dragon knife into {2D}'s head.",
	'{1D} begs for {2K} to kill them. They reluctantly oblige, killing {1D}.',
	'{1K} and {2K} work together to kill {3D}.',
	'{1K} strangles {2D} after engaging in a fist fight.',
	"{1K} shoots a Dark bow spec into {2D}'s head.",
	'{1D} bleeds out due to untreated injuries.',
	'{1D} cannot handle the circumstances and logs out.',
	'{1D} unknowingly eats cavada berries.',
	'{1K} silently specs out {2D}.',
	"{1K} poisons {2D}'s food, killing them.",
	'{1K} decapitates {2D} with an AGS spec.',
	'{1D} dies from an infection.',
	'{1K} spears {2D} in the abdomen.',
	'{1K} sets {2D} on fire with Flames of Zamorak.',
	'{1D} falls into a pit and dies.',
	'{1K} stabs {2D} while their back is turned.',
	'{1K} severely injures {2D}, but puts them out of their misery.',
	'{1K} severely injures {2D} and leaves them to die.',
	"{1K} bashes {2D}'s head in with a mace.",
	'{1D} attempts to climb a tree, but falls to their death.',
	'{1K} pushes {2D} off a cliff during a knife fight.',
	"{1K} throws a knife into {2D}'s chest.",
	"{1K}'s trap kills {2D}.",
	'{1K} kills {2D} while they are sleeping.',
	'{1D} is unable to convince {2K} to not kill them.',
	'{1K} convinces {2D} to not kill them, only to kill {2D} instead.',
	'{1D} falls into a frozen lake and drowns.',
	'{1K}, {2}, and {3D} start fighting, but {2} runs away as {1K} kills {3D}.',
	'{1K} kills {2D} with their own weapon.',
	'{1K} overpowers {2D}, killing them.',
	'{1K} sets an explosive off, killing {2D}.',
	'{1K} sets an explosive off, killing {2D}, and {3D}.',
	'{1K} sets an explosive off, killing {2D}, {3D}, and {4D}.',
	'{1K} sets an explosive off, killing {2D}, {3D}, {4D} and {5D}.',
	'{1K} kills {2D} as they try to run.',
	'{1D} and {2D} threaten a double suicide. It fails and they die.',
	'{1D}, {2D}, {3D}, and {4D} form a suicide pact, killing themselves.',
	'{1D} dies from hypothermia.',
	'{1D} dies from hunger.',
	'{1D} dies from thirst.',
	'{1K} kills {2D} with a hatchet.',
	'{1K} and {2K} fight {3D} and {4D}. {1K} and {2K} survive.',
	'{1D} and {2D} fight {3K} and {4K}. {3K} and {4K} survive.',
	'{1D} dies trying to escape the arena.',
	'{1D} dies of dysentery.',
	'{1D} accidently detonates a land mine while trying to arm it.',
	'{1D} attacks {2}, but {3K} protects them, killing {1D}.',
	'{1K} ambushes {2D} and kills them.',
	'{1D} accidently sets off a wild chinchompa, getting blown to pieces.',
	"{1K} severely slices {2D} with a Vesta's longsword.",
	'{1K} strangles {2D} with an Abyssal whip.',
	'{1K} kills {2D} for their supplies.',
	'{1K} shoots an arrow at {2}, but misses and kills {3D} instead.',
	"{1K} shoots a poisonous blow dart into {2D}'s neck, slowly killing them.",
	'{1K}, {2K}, and {3K} successfully ambush and kill {4D}, {5D}, and {6D}.',
	'{1D}, {2D}, and {3D} unsuccessfully ambush {4K}, {5K}, and {6K}, who kill them instead.',
	"{1K} stabs {2D} with a Vesta's spear.",
	'{1} forces {2K} to kill {3D} or {4}. They decide to kill {3D}.',
	'{1} forces {2K} to kill {3} or {4D}. They decide to kill {4D}.',
	'{1K} forces {2D} to kill {3} or {4}. They refuse to kill, so {1K} kills them instead.',
	"{1D} poisons {2}'s potion, but mistakes it for their own and dies.",
	"{1K} poisons {2D}'s potion. They drink it and die.",
	'{1K} stabs {2D} in the back with a trident.',
	'{1D} attempts to climb a tree, but falls on {2D}, killing them both.',
	'{1K}, {2D}, and {3D} get into a fight. {1K} triumphantly kills them both.',
	'{1D}, {2K}, and {3D} get into a fight. {2K} triumphantly kills them both.',
	'{1D}, {2D}, and {3K} get into a fight. {3K} triumphantly kills them both.',
	"{1K} kills {2D} with a Statius's warhammer.",
	'{1K}, {2K}, {3K}, {4K}, and {5K} track down and kill {6D}.',
	'{1K}, {2K}, {3K}, and {4K} track down and kill {5D}.',
	'{1K}, {2K}, and {3K} track down and kill {4D}.',
	'{1K} and {2K} track down and kill {3D}.',
	'{1K} tracks down and kills {2D}.',
	'{1K} repeatedly stabs {2D} to death with Dragon daggers.',
	'{1} writes in their journal.',
	'{1} watches {2} sitting at their campfire, and considers killing them.'
].map(string => new LastManStandingUsage(string));
