import { KlasaUser } from 'klasa';

export default class LastManStandingUsage {
	public contestants = 0;
	public deaths: Set<number> = new Set();
	private readonly parts: (string | number)[] = [];

	public constructor(usage: string) {
		this.parse(usage);
	}

	public display(...values: KlasaUser[]) {
		return this.parts
			.map(part => (typeof part === 'number' ? values[part].username : part))
			.join('');
	}

	public parse(usage: string): void {
		let current = '';
		for (let i = 0, char; i < usage.length; i++) {
			char = usage.charAt(i);
			if (char === '{') {
				// If there was text, push buffer
				if (current) {
					this.parts.push(current);
					current = '';
				}

				// Parse tag {NT?}
				const n = Number(usage.charAt(++i));

				// If N > contestants, assign contestants to N
				if (n > this.contestants) this.contestants = n;

				// If NT, add death
				if (usage.charAt(++i) === 'T') {
					this.deaths.add(n - 1);
					i++;
				}

				this.parts.push(n - 1);
			} else {
				current += char;
			}
		}

		if (current) this.parts.push(current);
	}
}

export const LMS_BLOODBATH = [
	'{1} grabs a DDS.',
	'{1} grabs an Abyssal whip and retreats.',
	'{1} and {2} fight for a whip. {1} gives up and retreats.',
	'{1} and {2} fight for a whip. {2} gives up and retreats.',
	"{1} finds a Heavy ballista, some Javelins, and an Ava's assembler.",
	'{1} runs into upstairs in a building and hides.',
	'{1} takes a handful of Morrigan Javelins.',
	"{1} rips a Zuriel's staff out of {2}'s hands.",
	'{1} finds a vial full of Saradomin brew.',
	'{1} Loots a death pile for resources.',
	'{1} gathers as much food as they can.',
	'{1} grabs a Vesta longsword.',
	'{1} takes a Gharazi Rapier from inside the Trinity Outpost.',
	'{1} finds a Crate with an Infernal cape.',
	'{1} clutches a Bloody key and runs away.',
	'{1} takes a AGS from inside the Moser Settlement.',
	'{1}, {2}, and {3} work together to get as many supplies as possible.',
	'{1} runs away with a pair of Eternal boots and some sharks.',
	'{1} snatches a vial of Super restore and a Stamina potion.',
	'{1} finds a supply box full of Granite mauls & supplies.',
	'{1} searches a supply box, not realizing it is empty.',
	'{1} DDS specs {2} for a single Karambwan.',
	'{1}, {2}, {3}, and {4} share everything they gathered before running.',
	'{1} retrieves a Staff of the Dead from the Debtor hideout .',
	"{1} grabs a Stamina potion while {2} gets Ahrim's robes.",
	'{1} scares {2} away from the Moser Settlement.',
	'{1} grabs a Dragonfire shield from the ground on The Mountain.',
	'{1} snatches a pair of Dragon claws.',
	'{1} grabs a lone pair of pants.',
	'{1T} steps out of the safezone too soon and gets killed by the fog.',
	"{1} throws a Morrigan Javelin into {2T}'s head.",
	'{1T} gets 6 Hour logged and dies.',
	'{1} catches {2T} off guard and AGS specs a 73.',
	'{1} and {2} work together to drown {3T}.',
	'{1} smites {2T} and kills them after engaging in a fist fight.',
	"{1} shoots a Dragon arrow into {2T}'s head.",
	'{1T} cannot handle the circumstances and runs in the fog.',
	"{1} bashes {2T}'s head against a Granite maul several times.",
	"{1} snaps {2T}'s neck with their bare hands.",
	'{1} decapitates {2T} with a Ghrazi Rapier.',
	"{1} plunges a Dragon dagger in {2T}'s abdomen.",
	'{1} sets {2T} on fire with an Infernal cape.',
	'{1T} falls into a pit and dies.',
	'{1} stabs {2T} while their back is turned.',
	'{1} severely injures {2T}, but puts them out of their misery.',
	'{1} severely injures {2T} and leaves them to die.',
	"{1} bashes {2T}'s head in with an Elder maul.",
	'{1} pushes {2T} off a cliff during a whip fight.',
	"{1} throws a Dragon knife into {2T}'s chest.",
	'{1T} is unable to convince {2} to not kill them.',
	'{1} convinces {2T} to not kill them, only to kill {2T} instead.',
	'{1T} falls into the River and drowns.',
	'{1}, {2}, and {3T} start fighting, but {2} runs away as {1} kills {3T}.',
	'{1} kills {2T} with their own spec weapon.',
	'{1} overpowers {2T}, killing them.',
	'{1} throws a Chinchompa, killing {2T}.',
	'{1} throws a Chinchompa, killing {2T}, and {3T}.',
	'{1} throws a Chinchompa, killing {2T}, {3T}, and {4T}.',
	'{1} throws a Chinchompa, killing {2T}, {3T}, {4T} and {5T}.',
	'{1} kills {2T} as they try to run.',
	'{1T} and {2T} threaten a double suicide. It fails and they die.',
	'{1T}, {2T}, {3T}, and {4T} form a suicide pact, and run in the fog.',
	'{1} kills {2T} with a Dragon thrownaxe.',
	'{1} and {2} fight {3T} and {4T}. {1} and {2} survive.',
	'{1T} and {2T} fight {3} and {4}. {3} and {4} survive.',
	'{1T} attacks {2}, but {3} protects them, killing {1T}.',
	'{1} severely slices {2T} with an Armadyl godsword.',
	'{1} strangles {2T} with an Abyssal whip.',
	'{1} kills {2T} for their supplies.',
	'{1} shoots a Dragon Javelin at {2}, but misses and kills {3T} instead.',
	"{1} shoots a poisonous Dragon dart into {2T}'s neck, slowly killing them.",
	'{1} stabs {2T} with a Ghrazi rapier.',
	'{1} stabs {2T} in the back with a Zuriels Staff.',
	'{1}, {2T}, and {3T} get into a fight. {1} triumphantly kills them both.',
	'{1T}, {2}, and {3T} get into a fight. {2} triumphantly kills them both.',
	'{1T}, {2T}, and {3} get into a fight. {3} triumphantly kills them both.',
	'{1} finds {2T} hiding in the Debtor Hideout and kills them.',
	'{1T} finds {2} hiding in the Debtor Hideout, but {2} kills them.',
	'{1} kills {2T} with a Dragon scimitar.',
	'{1} and {2T} fight for a crate.{1} strangles {2T} with a whip and runs.',
	'{1T} and {2} fight for a crate.{2} strangles {1T} with a whip and runs.',
	'{1} repeatedly stabs {2T} to death with a Ghrazi Rapier.',
	'{1T} trips over while running from the fog, and is killed by {2}.',
	'{1} trips over while running from the fog, {2} picks them up, they run off together.',
	"{1} aims a Dragon arrow at {2}'s head and shoots, {3T} jumps in the way and sacrifices their life to save them."
].map(string => new LastManStandingUsage(string));

export const LMS_DAY = [
	'{1} goes hunting.',
	'{1} injures themself.',
	'{1} explores the arena.',
	'{1} scares {2} off.',
	"{1} diverts {2}'s attention and runs away.",
	'{1} stalks {2}.',
	'{1} eats a shark.',
	'{1} camouflauges themself in the bushes.',
	"{1} pickpockets {2} while they aren't looking.",
	'{1} finds a dragon spear.',
	'{1} discovers a cave.',
	'{1} attacks {2}, but they manage to escape.',
	'{1} chases {2}.',
	'{1} runs away from {2}.',
	'{1} receives a Twisted bow from an unknown sponsor.',
	'{1} receives a super combat potion from an unknown sponsor.',
	'{1} receives a bag of potions from an unknown sponsor.',
	'{1} receives fresh food from an unknown sponsor.',
	'{1} defeats {2} in a fight, but spares their life.',
	'{1} and {2} work together for now.',
	'{1} begs for {2} to kill them. They refuse, keeping {1} alive.',
	'{1} tries to stay hidden for the entire day.',
	"{1}, {2}, {3}, and {4} raid {5}'s chest while they are looting.",
	'{1} overhears {2} and {3} talking in the distance.',
	'{1} practices their archery.',
	'{1} thinks about home.',
	'{1} is pricked by thorns while picking cavada berries.',
	'{1} tries to spear fish with a trident.',
	'{1} searches for firewood.',
	'{1} and {2} split up to search for supplies.',
	'{1} picks flowers.',
	"{1} tends to {2}'s wounds.",
	'{1} sees smoke rising in the distance, but decides not to investigate.',
	'{1} sprains their ankle while running away from {2}.',
	'{1} makes a crossbow.',
	'{1} travels to higher ground.',
	'{1} discovers a river.',
	'{1} hunts for other contestants.',
	'{1} and {2} hunt for other contestants.',
	'{1}, {2}, and {3} hunt for other contestants.',
	'{1}, {2}, {3}, and {4} hunt for other contestants.',
	'{1}, {2}, {3}, {4}, and {5} hunt for other contestants.',
	'{1} receives a bag of chinchompas from an unknown sponsor.',
	'{1} questions their sanity.',
	'{1} forces {2} to eat pant.',
	'{1} forces {2T} to eat pant. {2T} chokes and dies.',
	'{1} catches {2T} off guard and kills them.',
	"{1} throws a dragon knife into {2T}'s head.",
	'{1T} begs for {2} to kill them. They reluctantly oblige, killing {1T}.',
	'{1} and {2} work together to spec out {3T}.',
	'{1} strangles {2T} after engaging in a risk fight.',
	"{1} shoots an arrow into {2T}'s head.",
	'{1T} bleeds out due to untreated injuries.',
	'{1T} cannot handle the circumstances and logs out.',
	"{1} bashes {2T}'s head against a rock several times.",
	'{1T} unknowingly eats cavada berries.',
	"{1} silently snaps {2T}'s neck.",
	"{1} taints {2T}'s food, killing them.",
	'{1} decapitates {2T} with an AGS spec.',
	'{1T} dies from an infection.',
	'{1} spears {2T} in the abdomen.',
	'{1} sets {2T} on fire with Flames of Zamorak.',
	'{1T} falls into a pit and dies.',
	"{1} DDS specs {2T} while they're purchasing supplies.",
	'{1} severely injures {2T}, but puts them out of their misery.',
	'{1} severely injures {2T} and leaves them to die.',
	"{1} bashes {2T}'s head in with a Dragon mace.",
	'{1T} attempts to climb a tree, but falls to their death.',
	'{1} pushes {2T} off a cliff during a knife fight.',
	"{1} throws a dragon knife into {2T}'s chest.",
	"{1}'s trap kills {2T}.",
	'{1} kills {2T} while they are resting.',
	'{1T} is unable to convince {2} to not kill them.',
	'{1} convinces {2T} to not kill them, only to kill {2T} instead.',
	'{1T} unknowingly runs into the fog and dies.',
	'{1}, {2}, and {3T} start fighting, but {2} runs away as {1} kills {3T}.',
	'{1} kills {2T} with their own weapon.',
	'{1} overpowers {2T}, killing them.',
	'{1} throws a chinchompa, killing {2T}.',
	'{1} throws a chinchompa, killing {2T}, and {3T}.',
	'{1} throws a chinchompa, killing {2T}, {3T}, and {4T}.',
	'{1} throws a chinchompa, killing {2T}, {3T}, {4T} and {5T}.',
	'{1} kills {2T} as they try to run.',
	'{1T} and {2T} threaten a double suicide. It fails and they die.',
	'{1T}, {2T}, {3T}, and {4T} form a suicide pact, killing themselves.',
	'{1T} dies from poison.',
	'{1T} dies from venom.',
	'{1T} dies from disease.',
	"{1} kills {2T} with a Morrigan's throwing axe.",
	'{1} and {2} fight {3T} and {4T}. {1} and {2} survive.',
	'{1T} and {2T} fight {3} and {4}. {3} and {4} survive.',
	'{1T} dies in the fog trying to escape the arena.',
	'{1T} accidently detonates a chinchompa trying to throw it.',
	'{1T} attacks {2}, but {3} protects them, killing {1T}.',
	'{1} ambushes {2T} and kills them.',
	'{1T} accidently steps on a trap.',
	'{1} severely slices {2T} with an AGS spec.',
	'{1} strangles {2T} with an Abyssal whip.',
	'{1} kills {2T} for their supplies.',
	'{1} shoots an arrow at {2}, but misses and kills {3T} instead.',
	"{1} shoots a poisonous blow dart into {2T}'s neck, slowly killing them.",
	'{1}, {2}, and {3} successfully ambush and kill {4T}, {5T}, and {6T}.',
	'{1T}, {2T}, and {3T} unsuccessfully ambush {4}, {5}, and {6}, who kill them instead.',
	'{1} shoots {2T} with a Dark bow.',
	'{1} forces {2} to kill {3T} or {4}. They decide to kill {3T}.',
	'{1} forces {2} to kill {3} or {4T}. They decide to kill {4T}.',
	'{1} forces {2T} to kill {3} or {4}. They refuse to kill, so {1} kills them instead.',
	"{1T} poisons {2}'s potion, but mistakes it for their own and dies.",
	"{1} poisons {2T}'s potion. They drink it and die.",
	"{1} stabs {2T} in the back with a Vesta's longsword.",
	'{1T} attempts to climb a tree, but falls on {2T}, killing them both.',
	'{1}, {2T}, and {3T} get into a fight. {1} triumphantly kills them both.',
	'{1T}, {2}, and {3T} get into a fight. {2} triumphantly kills them both.',
	'{1T}, {2T}, and {3} get into a fight. {3} triumphantly kills them both.',
	'{1} kills {2T} with a Ghrazi rapier.',
	'{1}, {2}, {3}, {4}, and {5} track down and kill {6T}.',
	'{1}, {2}, {3}, and {4} track down and kill {5T}.',
	'{1}, {2}, and {3} track down and kill {4T}.',
	'{1} and {2} track down and kill {3T}.',
	'{1} tracks down and kills {2T}.',
	'{1} repeatedly stabs {2T} to death with Draggon dagger.',
	'{1} doodles in the dirt.',
	'{1} chases a butterfly.',
	'{1T} falls off a cliff, and is impaled by a stick.',
	'{1} runs into {2}, they decide to team up.',
	'{1} sees {2} through the trees, and plans on killing them.',
	'{1} sneaks up behind {2T}, and barrages them.',
	'{1T} challenges {2} to a fight, and promptly dies.',
	'{1} murders their partner, {2T}, to have more supplies for themself.'
].map(string => new LastManStandingUsage(string));

export const LMS_NIGHT = [
	'{1} starts a fire.',
	'{1} searches for a bloody chest.',
	'{1} loses sight of where they are.',
	'{1} hides in a building to rest.',
	'{1} eats all their food.',
	'{1} and {2} tell stories about themselves to each other.',
	'{1} tends to their wounds.',
	'{1} sees a fire, but stays hidden.',
	'{1} screams for help.',
	'{1} stays awake all night.',
	'{1} passes out from exhaustion.',
	'{1} cooks their food before putting their fire out.',
	'{1} and {2} run into each other and decide to truce for the night.',
	'{1} fends {2}, {3}, and {4} away from their fire.',
	'{1}, {2}, and {3} discuss the games and what might happen in the morning.',
	'{1} cries themself to sleep.',
	'{1} tries to treat their infection.',
	'{1} and {2} talk about the contestants still alive.',
	'{1} is awoken by nightmares.',
	'{1} and {2} huddle for warmth.',
	'{1} thinks about winning.',
	'{1}, {2}, {3}, and {4} tell each other ghost stories to lighten the mood.',
	'{1} looks at the night sky.',
	'{1} defeats {2} in a fight, but spares their life.',
	'{1} begs for {2} to kill them. They refuse, keeping {1} alive.',
	"{1} destroys {2}'s supplies while they are asleep.",
	'{1} lets {2} into their shelter.',
	'{1} receives a Dragon hatchet from an unknown sponsor.',
	'{1} receives a combat potion from an unknown sponsor.',
	'{1} receives a bag of potions from an unknown sponsor.',
	'{1} receives food from an unknown sponsor.',
	'{1} attempts to start a fire, but is unsuccessful.',
	'{1} thinks about home.',
	"{1} tends to {2}'s wounds.",
	'{1} quietly hums.',
	'{1}, {2}, and {3} cheerfully sing songs together.',
	'{1} and {2} hold hands.',
	'{1} convinces {2} to snuggle with them.',
	'{1} receives a chinchompa from an unknown sponsor.',
	'{1} questions their sanity.',
	'{1} forces {2} to eat pant.',
	'{1} forces {2T} to eat pant. {2T} chokes and dies.',
	'{1} catches {2T} off guard and kills them.',
	"{1} throws a dragon knife into {2T}'s head.",
	'{1T} begs for {2} to kill them. They reluctantly oblige, killing {1T}.',
	'{1} and {2} work together to kill {3T}.',
	'{1} strangles {2T} after engaging in a fist fight.',
	"{1} shoots a Dark bow spec into {2T}'s head.",
	'{1T} bleeds out due to untreated injuries.',
	'{1T} cannot handle the circumstances and logs out.',
	'{1T} unknowingly eats cavada berries.',
	'{1} silently specs out {2T}.',
	"{1} poisons {2T}'s food, killing them.",
	'{1} decapitates {2T} with an AGS spec.',
	'{1T} dies from an infection.',
	'{1} spears {2T} in the abdomen.',
	'{1} sets {2T} on fire with Flames of Zamorak.',
	'{1T} falls into a pit and dies.',
	'{1} stabs {2T} while their back is turned.',
	'{1} severely injures {2T}, but puts them out of their misery.',
	'{1} severely injures {2T} and leaves them to die.',
	"{1} bashes {2T}'s head in with a mace.",
	'{1T} attempts to climb a tree, but falls to their death.',
	'{1} pushes {2T} off a cliff during a knife fight.',
	"{1} throws a knife into {2T}'s chest.",
	"{1}'s trap kills {2T}.",
	'{1} kills {2T} while they are sleeping.',
	'{1T} is unable to convince {2} to not kill them.',
	'{1} convinces {2T} to not kill them, only to kill {2T} instead.',
	'{1T} falls into a frozen lake and drowns.',
	'{1}, {2}, and {3T} start fighting, but {2} runs away as {1} kills {3T}.',
	'{1} kills {2T} with their own weapon.',
	'{1} overpowers {2T}, killing them.',
	'{1} sets an explosive off, killing {2T}.',
	'{1} sets an explosive off, killing {2T}, and {3T}.',
	'{1} sets an explosive off, killing {2T}, {3T}, and {4T}.',
	'{1} sets an explosive off, killing {2T}, {3T}, {4T} and {5T}.',
	'{1} kills {2T} as they try to run.',
	'{1T} and {2T} threaten a double suicide. It fails and they die.',
	'{1T}, {2T}, {3T}, and {4T} form a suicide pact, killing themselves.',
	'{1T} dies from hypothermia.',
	'{1T} dies from hunger.',
	'{1T} dies from thirst.',
	'{1} kills {2T} with a hatchet.',
	'{1} and {2} fight {3T} and {4T}. {1} and {2} survive.',
	'{1T} and {2T} fight {3} and {4}. {3} and {4} survive.',
	'{1T} dies trying to escape the arena.',
	'{1T} dies of dysentery.',
	'{1T} accidently detonates a land mine while trying to arm it.',
	'{1T} attacks {2}, but {3} protects them, killing {1T}.',
	'{1} ambushes {2T} and kills them.',
	'{1T} accidently sets off a wild chinchompa, getting blown to pieces.',
	"{1} severely slices {2T} with a Vesta's longsword.",
	'{1} strangles {2T} with an Abyssal whip.',
	'{1} kills {2T} for their supplies.',
	'{1} shoots an arrow at {2}, but misses and kills {3T} instead.',
	"{1} shoots a poisonous blow dart into {2T}'s neck, slowly killing them.",
	'{1}, {2}, and {3} successfully ambush and kill {4T}, {5T}, and {6T}.',
	'{1T}, {2T}, and {3T} unsuccessfully ambush {4}, {5}, and {6}, who kill them instead.',
	"{1} stabs {2T} with a Vesta's spear.",
	'{1} forces {2} to kill {3T} or {4}. They decide to kill {3T}.',
	'{1} forces {2} to kill {3} or {4T}. They decide to kill {4T}.',
	'{1} forces {2T} to kill {3} or {4}. They refuse to kill, so {1} kills them instead.',
	"{1T} poisons {2}'s potion, but mistakes it for their own and dies.",
	"{1} poisons {2T}'s potion. They drink it and die.",
	'{1} stabs {2T} in the back with a trident.',
	'{1T} attempts to climb a tree, but falls on {2T}, killing them both.',
	'{1}, {2T}, and {3T} get into a fight. {1} triumphantly kills them both.',
	'{1T}, {2}, and {3T} get into a fight. {2} triumphantly kills them both.',
	'{1T}, {2T}, and {3} get into a fight. {3} triumphantly kills them both.',
	"{1} kills {2T} with a Statius's warhammer.",
	'{1}, {2}, {3}, {4}, and {5} track down and kill {6T}.',
	'{1}, {2}, {3}, and {4} track down and kill {5T}.',
	'{1}, {2}, and {3} track down and kill {4T}.',
	'{1} and {2} track down and kill {3T}.',
	'{1} tracks down and kills {2T}.',
	'{1} repeatedly stabs {2T} to death with Dragon daggers.',
	'{1} writes in their journal.',
	'{1} watches {2} sitting at their campfire, and considers killing them.'
].map(string => new LastManStandingUsage(string));
