import { EItem } from 'oldschooljs';

export const ScrollCases = {
	name: 'Scroll Cases',
	items: [
		EItem.MINOR_BEGINNER_SCROLL_CASE,
		EItem.MAJOR_BEGINNER_SCROLL_CASE,
		EItem.MINOR_EASY_SCROLL_CASE,
		EItem.MAJOR_EASY_SCROLL_CASE,
		EItem.MINOR_MEDIUM_SCROLL_CASE,
		EItem.MAJOR_MEDIUM_SCROLL_CASE,
		EItem.MINOR_HARD_SCROLL_CASE,
		EItem.MAJOR_HARD_SCROLL_CASE,
		EItem.MINOR_ELITE_SCROLL_CASE,
		EItem.MAJOR_ELITE_SCROLL_CASE,
		EItem.MINOR_MASTER_SCROLL_CASE,
		EItem.MAJOR_MASTER_SCROLL_CASE,
		EItem.MIMIC_SCROLL_CASE
	]
};
