import { bsoGlobalGearPresets } from '@/lib/bso/gear/bsoGearPresets.js';

import type { GearSetupType } from '@oldschoolgg/gear';
import { itemID } from 'oldschooljs';

import type { GearPreset } from '@/prisma/main.js';

export type GlobalPreset = GearPreset & { defaultSetup: GearSetupType; aliases?: string[] };

export const globalPresets: GlobalPreset[] = [
	{
		name: 'graceful',
		user_id: '123',
		head: itemID('Graceful hood'),
		neck: null,
		body: itemID('Graceful top'),
		legs: itemID('Graceful legs'),
		cape: itemID('Graceful cape'),
		two_handed: null,
		hands: itemID('Graceful gloves'),
		feet: itemID('Graceful boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'construction',
		user_id: '123',
		head: itemID("Carpenter's helmet"),
		neck: null,
		body: itemID("Carpenter's shirt"),
		legs: itemID("Carpenter's trousers"),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID("Carpenter's boots"),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'thieving',
		user_id: '123',
		head: itemID('Rogue mask'),
		neck: null,
		body: itemID('Rogue top'),
		legs: itemID('Rogue trousers'),
		cape: null,
		two_handed: null,
		hands: itemID('Rogue gloves'),
		feet: itemID('Rogue boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'clue_hunter',
		user_id: '123',
		head: itemID('Helm of raedwald'),
		neck: null,
		body: itemID('Clue hunter garb'),
		legs: itemID('Clue hunter trousers'),
		cape: itemID('Clue hunter cloak'),
		two_handed: null,
		hands: itemID('Clue hunter gloves'),
		feet: itemID('Clue hunter boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'fishing',
		aliases: ['angler'],
		user_id: '123',
		head: itemID('Angler hat'),
		neck: null,
		body: itemID('Angler top'),
		legs: itemID('Angler waders'),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID('Angler boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'firemaking',
		user_id: '123',
		head: itemID('Pyromancer hood'),
		neck: null,
		body: itemID('Pyromancer garb'),
		legs: itemID('Pyromancer robe'),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID('Pyromancer boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'mining',
		user_id: '123',
		head: itemID('Prospector helmet'),
		neck: null,
		body: itemID('Prospector jacket'),
		legs: itemID('Prospector legs'),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID('Prospector boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'woodcutting',
		user_id: '123',
		head: itemID('Lumberjack hat'),
		neck: null,
		body: itemID('Lumberjack top'),
		legs: itemID('Lumberjack legs'),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID('Lumberjack boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'farming',
		user_id: '123',
		head: itemID("Farmer's strawhat"),
		neck: null,
		body: itemID("Farmer's jacket"),
		legs: itemID("Farmer's boro trousers"),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID("Farmer's boots"),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'runecraft',
		user_id: '123',
		head: itemID('Hat of the eye'),
		neck: null,
		body: itemID('Robe top of the eye'),
		legs: itemID('Robe bottoms of the eye'),
		cape: null,
		two_handed: null,
		hands: null,
		feet: itemID('Boots of the eye'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	{
		name: 'smithing',
		user_id: '123',
		head: null,
		neck: null,
		body: itemID('Smiths tunic'),
		legs: itemID('Smiths trousers'),
		cape: null,
		two_handed: null,
		hands: itemID('Smiths gloves'),
		feet: itemID('Smiths boots'),
		shield: null,
		weapon: null,
		ring: null,
		ammo: null,
		ammo_qty: null,
		times_equipped: 0,
		defaultSetup: 'skilling',
		pinned_setup: null
	},
	...bsoGlobalGearPresets
];
