import { Tasks } from '../constants';
import { ActivityTypeEnum } from '.prisma/client';

export function taskNameFromType(activityType: ActivityTypeEnum): Tasks {
	switch (activityType) {
		case ActivityTypeEnum.Agility:
			return Tasks.AgilityActivity;
		case ActivityTypeEnum.ClueCompletion:
			return Tasks.ClueActivity;
		case ActivityTypeEnum.Cooking:
			return Tasks.CookingActivity;
		case ActivityTypeEnum.MonsterKilling:
			return Tasks.MonsterActivity;
		case ActivityTypeEnum.GroupMonsterKilling:
			return Tasks.GroupMonsterActivity;
		case ActivityTypeEnum.Fishing:
			return Tasks.FishingActivity;
		case ActivityTypeEnum.Mining:
			return Tasks.MiningActivity;
		case ActivityTypeEnum.Smelting:
			return Tasks.SmeltingActivity;
		case ActivityTypeEnum.Smithing:
			return Tasks.SmithingActivity;
		case ActivityTypeEnum.Woodcutting:
			return Tasks.WoodcuttingActivity;
		case ActivityTypeEnum.Firemaking:
			return Tasks.FiremakingActivity;
		case ActivityTypeEnum.Crafting:
			return Tasks.CraftingActivity;
		case ActivityTypeEnum.Questing:
			return Tasks.QuestingActivity;
		case ActivityTypeEnum.Runecraft:
			return Tasks.RunecraftActivity;
		case ActivityTypeEnum.Burying:
			return Tasks.BuryingActivity;
		case ActivityTypeEnum.Offering:
			return Tasks.OfferingActivity;
		case ActivityTypeEnum.FightCaves:
			return Tasks.FightCavesActivity;
		case ActivityTypeEnum.Fletching:
			return Tasks.FletchingActivity;
		case ActivityTypeEnum.Wintertodt:
			return Tasks.WintertodtActivity;
		case ActivityTypeEnum.Tempoross:
			return Tasks.TemporossActivity;
		case ActivityTypeEnum.Alching:
			return Tasks.AlchingActivity;
		case ActivityTypeEnum.Herblore:
			return Tasks.HerbloreActivity;
		case ActivityTypeEnum.Nightmare:
			return Tasks.NightmareActivity;
		case ActivityTypeEnum.AnimatedArmour:
			return Tasks.AnimatedArmourActivity;
		case ActivityTypeEnum.Cyclops:
			return Tasks.CyclopsActivity;
		case ActivityTypeEnum.Sawmill:
			return Tasks.SawmillActivity;
		case ActivityTypeEnum.Sepulchre:
			return Tasks.SepulchreActivity;
		case ActivityTypeEnum.Plunder:
			return Tasks.PlunderActivity;
		case ActivityTypeEnum.FishingTrawler:
			return Tasks.FishingTrawler;
		case ActivityTypeEnum.Zalcano:
			return Tasks.ZalcanoActivity;
		case ActivityTypeEnum.Pickpocket:
			return Tasks.PickpocketActivity;
		case ActivityTypeEnum.Farming:
			return Tasks.FarmingActivity;
		case ActivityTypeEnum.TitheFarm:
			return Tasks.TitheFarmActivity;
		case ActivityTypeEnum.BarbarianAssault:
			return Tasks.BarbarianAssault;
		case ActivityTypeEnum.AgilityArena:
			return Tasks.AgilityArena;
		case ActivityTypeEnum.ChampionsChallenge:
			return Tasks.ChampionsChallenge;
		case ActivityTypeEnum.Hunter:
			return Tasks.HunterActivity;
		case ActivityTypeEnum.Birdhouse:
			return Tasks.BirdhouseActivity;
		case ActivityTypeEnum.AerialFishing:
			return Tasks.AerialFishingActivity;
		case ActivityTypeEnum.DriftNet:
			return Tasks.DriftNetActivity;
		case ActivityTypeEnum.Construction:
			return Tasks.ConstructionActivity;
		case ActivityTypeEnum.MahoganyHomes:
			return Tasks.MahoganyHomes;
		case ActivityTypeEnum.Enchanting:
			return Tasks.Enchanting;
		case ActivityTypeEnum.Casting:
			return Tasks.Casting;
		case ActivityTypeEnum.GloryCharging:
			return Tasks.GloryCharging;
		case ActivityTypeEnum.WealthCharging:
			return Tasks.WealthCharging;
		case ActivityTypeEnum.GnomeRestaurant:
			return Tasks.GnomeRestaurant;
		case ActivityTypeEnum.SoulWars:
			return Tasks.SoulWars;
		case ActivityTypeEnum.RoguesDenMaze:
			return Tasks.RoguesDenMaze;
		case ActivityTypeEnum.Gauntlet:
			return Tasks.Gauntlet;
		case ActivityTypeEnum.CastleWars:
			return Tasks.CastleWars;
		case ActivityTypeEnum.MageArena:
			return Tasks.MageArena;
		case ActivityTypeEnum.Raids:
			return Tasks.Raids;
		case ActivityTypeEnum.Collecting:
			return Tasks.Collecting;
		case ActivityTypeEnum.MageTrainingArena:
			return Tasks.MageTrainingArena;
		case ActivityTypeEnum.BlastFurnace:
			return Tasks.BlastFurnaceActivity;
		case ActivityTypeEnum.MageArena2:
			return Tasks.MageArena2;
		case ActivityTypeEnum.BigChompyBirdHunting:
			return Tasks.BigChompyBirdHunting;
		case ActivityTypeEnum.DarkAltar:
			return Tasks.DarkAltar;
		case ActivityTypeEnum.Trekking:
			return Tasks.TrekkingActivity;
		case ActivityTypeEnum.Revenants:
			return Tasks.RevenantsActivity;
		case ActivityTypeEnum.PestControl:
			return Tasks.PestControl;
		case ActivityTypeEnum.VolcanicMine:
			return Tasks.VolcanicMine;
		case ActivityTypeEnum.KourendFavour:
			return Tasks.KourendFavour;
		case ActivityTypeEnum.Inferno:
			return Tasks.Inferno;
	}
}
