import getOSItem from '../../util/getOSItem';
import { DisassemblySourceGroup } from '..';

const i = getOSItem;

export const Clothing: DisassemblySourceGroup = {
	name: 'Clothing',
	items: [
		{
			item: [
				'Black tricorn hat',
				'Black satchel',
				'Black navy slacks',
				'Black naval shirt',
				'Black headband',
				'Black elegant shirt',
				'Black elegant legs',
				'Black dragon mask',
				'Black desert shirt',
				'Black beret',
				'Black boater',
				'Black cavalier',
				'Black desert robe',
				'Black unicorn mask',
				'Blue beret',
				'Blue boater',
				'Blue boots',
				'Blue dragon mask',
				'Blue elegant blouse',
				'Blue elegant legs',
				'Blue elegant shirt',
				'Blue elegant skirt',
				'Blue goblin mail',
				'Blue hat',
				'Blue naval shirt',
				'Blue navy slacks',
				'Blue robe bottoms',
				'Blue robe top',
				'Blue tricorn hat',
				'Bonesack',
				'Bow-sword',
				'Brown naval shirt',
				'Brown navy slacks',
				'Brown tricorn hat',
				"Builder's boots",
				"Builder's shirt",
				"Builder's trousers",
				'Cap and goggles',
				"Chef's hat",
				'Crab claw',
				'Crab helmet',
				'Cream boots',
				'Cream hat',
				'Cream robe bottoms',
				'Cream robe top',
				'Fremennik boots',
				'Fremennik hat',
				'Fremennik robe',
				'Fremennik skirt',
				'Gardening boots',
				'Gnome goggles',
				'Gnomeball',
				'Goblin mail',
				'Green hat',
				'Green naval shirt',
				'Green navy slacks',
				'Green robe bottoms',
				'Green robe top',
				'Green satchel',
				'Green tricorn hat',
				'Grey naval shirt',
				'Grey navy slacks',
				'Grey tricorn hat',
				'Ham boots',
				'Ham cloak',
				'Ham gloves',
				'Ham hood',
				'Ham robe',
				'Ham shirt',
				'Hard hat',
				'Pink boots',
				'Pink hat',
				'Pink robe bottoms',
				'Pink robe top',
				'Pink skirt',
				'Pirate boots',
				'Turquoise boots',
				'Turquoise hat',
				'Turquoise robe bottoms',
				'Turquoise robe top',
				'Vyrewatch legs',
				'Vyrewatch shoes',
				'Vyrewatch top',
				'Cat mask',
				'Dark cavalier',
				'Bronze dragon mask',
				'Flared trousers',
				'Green boater',
				'Green boots',
				'Green dragon mask',
				'Purple naval shirt',
				'Purple navy slacks',
				'Purple tricorn hat',
				'Red naval shirt',
				'Red navy slacks',
				'Red satchel',
				'Red tricorn hat',
				'Rock hammer',
				'Rock pick',
				'Rogue boots',
				'Rogue gloves',
				'Rogue mask',
				'Rogue top',
				'Rogue trousers',
				'Rose tinted lens',
				'Royal crown',
				'Green elegant blouse',
				'Green elegant legs',
				'Green elegant shirt',
				'Green elegant skirt',
				'Highwayman mask',
				'Iron dragon mask',
				'Jester cape',
				'Cape of skulls',
				'Fremennik brown shirt',
				'Villager robe',
				'Black robe',
				'Ankou top',
				'Elven legwear',
				'Yellow hat',
				'Musketeer pants',
				'Purple cape',
				'Grey robe top',
				'Villager armband',
				'Light tuxedo jacket',
				"Mummy's feet",
				'Blue skirt (t)',
				'Villager hat',
				'Leprechaun hat',
				'Ankou gloves',
				'Samurai gloves',
				'Fremennik red shirt',
				'Purple robe bottoms',
				"Mummy's hands",
				'Brown apron',
				'Dark tuxedo shoes',
				'Flappy meal',
				'Bear feet',
				'Hairyfloss',
				'Cake hat',
				'Piscarilius banner',
				'Piscarilius hood',
				'Piscarilius scarf',
				'Pink boater',
				'Pink cape',
				'Pink elegant blouse',
				'Pink elegant legs',
				'Pink elegant shirt',
				'Purple boater',
				'Purple boots',
				'Pink elegant skirt',
				'Priest gown',
				'Red robe bottoms',
				'Red robe top',
				'Priest gown',
				'Purple hat',
				'Purple robe top',
				'Purple gloves',
				'Pink headband',
				"Uri's hat",
				'Sandwich lady bottom',
				'Sandwich lady hat',
				'Sandwich lady top',
				'Ankou mask',
				'Ankou socks',
				"Ankou's leggings",
				'Villager sandals',
				'Villager sandals',
				'Villager sandals',
				'Gold elegant blouse',
				'Gold elegant legs',
				'Gold elegant shirt',
				'Gold elegant skirt',
				'Light trousers',
				'Light tuxedo cuffs',
				'Light tuxedo shoes',
				'Woven top',
				'Fremennik beige shirt',
				'Kyatt fur',
				'Kyatt hat',
				'Kyatt legs',
				'Lesser demon mask',
				'Kyatt top',
				'Fremennik black cloak',
				'Festive jumper (2021)',
				'Jungle camo legs',
				'Jungle camo top',
				'Jungle demon mask',
				'Fremennik blue cloak',
				'Demon feet',
				'Desert boots',
				'Fishing waders',
				'Crab hat',
				'Crier bell',
				'Crier coat',
				'Crier hat',
				'Devout boots',
				'Evil chicken feet',
				'Evil chicken head',
				'Evil chicken legs',
				'Evil chicken wings',
				'Fremennik blue shirt',
				'Fremennik brown cloak',
				'Dark trousers',
				'Dark tuxedo cuffs',
				'Dark tuxedo jacket',
				'Wolf cloak',
				'Musketeer hat',
				'Musketeer tabard',
				'Mycelium leggings web',
				'Mycelium poncho web',
				'Mycelium visor web',
				'Web cloak'
			].map(getOSItem),
			lvl: 1
		},
		{
			item: i('Mithril dragon mask'),
			lvl: 1
		},
		{
			item: i('Orange boater'),
			lvl: 1
		},
		{
			item: i('Pantaloons'),
			lvl: 1
		},
		{
			item: i('Penguin mask'),
			lvl: 1
		},
		{
			item: i("Pirate's hat"),
			lvl: 1
		},
		{
			item: i('Pith helmet'),
			lvl: 1
		},
		{
			item: i('Purple elegant blouse'),
			lvl: 1
		},
		{
			item: i('Purple elegant legs'),
			lvl: 1
		},
		{
			item: i('Purple elegant shirt'),
			lvl: 1
		},
		{
			item: i('Purple elegant skirt'),
			lvl: 1
		},

		{
			item: i('Red boater'),
			lvl: 1
		},
		{
			item: i('Red dragon mask'),
			lvl: 1
		},
		{
			item: i('Red elegant blouse'),
			lvl: 1
		},
		{
			item: i('Red elegant legs'),
			lvl: 1
		},
		{
			item: i('Red elegant shirt'),
			lvl: 1
		},
		{
			item: i('Red elegant skirt'),
			lvl: 1
		},
		{
			item: i('Red headband'),
			lvl: 1
		},

		{
			item: i('Rune dragon mask'),
			lvl: 1
		},
		{
			item: i('Samurai kasa'),
			lvl: 1
		},
		{
			item: i('Steel dragon mask'),
			lvl: 1
		},
		{
			item: i('Tan cavalier'),
			lvl: 1
		},

		{
			item: i('Top hat'),
			lvl: 1
		},

		{
			item: i('White beret'),
			lvl: 1
		},
		{
			item: i('White elegant blouse'),
			lvl: 1
		},
		{
			item: i('White elegant skirt'),
			lvl: 1
		},
		{
			item: i('White unicorn mask'),
			lvl: 1
		},
		{
			item: i('Wolf mask'),
			lvl: 1
		},
		{
			item: [
				'Swanky boots',
				'Darkmeyer hood',
				'Darkmeyer torso',
				'Darkmeyer trousers',
				'Darkmeyer boots',
				'Gorilla mask',
				'Thinker robes',
				'Thinker trousers',
				'Thinker gloves',
				'Thinker boots',
				"Prifddinian worker's robes",
				"Prifddinian worker's trousers",
				"Prifddinian worker's gloves",
				"Prifddinian worker's boots",
				"Prifddinian musician's robe top",
				"Prifddinian musician's robe bottom",
				"Prifddinian musician's gloves",
				"Prifddinian musician's boots",
				'Dervish head wrap (blue-gold)',
				'Dervish hood (red)',
				'Dervish robe (blue-gold)',
				'Dervish robe (red)',
				'Dervish trousers (blue-gold)',
				'Dervish skirt (red)',
				'Dervish shoes (blue-gold)',
				'Dervish shoes (red)',
				'Eastern knot',
				'Eastern bun',
				'Eastern robe (blue)',
				'Eastern kimono (blue)',
				'Eastern trousers (blue)',
				'Eastern skirt (blue)',
				'Eastern sandals (male)',
				'Eastern sandals (blue, female)',
				'Tribal ringlet (red, male)',
				'Tribal ringlet (red, female)',
				'Tribal shirt (red)',
				'Tribal top (red)',
				'Tribal trousers (red)',
				'Tribal skirt (red)',
				'Tribal shoes (red, male)',
				'Samba headdress (blue, male)',
				'Samba headdress (blue, female)',
				'Samba top (blue, male)',
				'Samba top (blue, female)',
				'Samba loincloth (blue, male)',
				'Samba loincloth (blue, female)',
				'Samba sandals (blue, male)',
				'Theatrical hat (blue)',
				'Theatrical earrings (blue)',
				'Theatrical tunic (blue, male)',
				'Theatrical tunic (blue, female)',
				'Theatrical trousers (blue)',
				'Theatrical skirt (blue)',
				'Theatrical shoes (blue, male)',
				'Theatrical shoes (blue, female)',
				"Pharaoh's nemes (green)",
				"Pharaoh's bun (green)",
				"Pharaoh's ankh (green)",
				"Pharaoh's top (green)",
				"Pharaoh's shendyt (green, male)",
				"Pharaoh's shendyt (green, female)",
				"Pharaoh's sandals (green, male)",
				"Pharaoh's sandals (green, female)",
				'Wushanko headdress (blue)',
				'Wushanko hat (blue)',
				'Wushanko top (blue)',
				'Wushanko jacket (blue)',
				'Wushanko skirt (blue)',
				'Wushanko trousers (blue)',
				'Wushanko shoes (blue, male)',
				'Wushanko shoes (blue, female)',
				'Silken turban (blue, male)',
				'Silken turban (blue, female)',
				'Silken top (blue, male)',
				'Silken top (blue, female)',
				'Silken trousers (blue)',
				'Silken skirt (blue)',
				'Silken boots (blue, male)',
				'Silken boots (blue, female)',
				"Colonist's hat (blue)",
				"Colonist's bonnet (blue)",
				"Colonist's coat (blue)",
				"Colonist's dress top (blue)",
				"Colonist's trousers (blue)",
				"Colonist's skirt (blue)",
				"Colonist's boots (blue)",
				"Colonist's shoes (blue)",
				'Feathered serpent headdress (blue, male)',
				'Feathered serpent headdress (blue, female)',
				'Feathered serpent body (blue, male)',
				'Feathered serpent body (blue, female)',
				'Feathered serpent skirt (blue, male)',
				'Feathered serpent skirt (blue, female)',
				'Feathered serpent boots (blue, female)',
				'Highland war paint (blue, male)',
				'Highland war paint (blue, female)',
				'Highland shirt (blue)',
				'Highland top (blue)',
				'Highland kilt (blue, male)',
				'Highland kilt (blue, female)',
				'Highland boots (blue, male)',
				'Highland boots (blue, female)',
				"Musketeer's hat (blue, male)",
				"Musketeer's hat (blue, female)",
				"Musketeer's tabard (blue)",
				"Musketeer's top (blue)",
				"Musketeer's trousers (blue, male)",
				"Musketeer's trousers (blue, female)",
				"Musketeer's boots (blue, male)",
				"Musketeer's boots (blue, female)",
				'Elf-style wig (black, male)',
				'Elf-style wig (black, female)',
				'Elf-style coat (black)',
				'Elf-style dress top (black)',
				'Elf-style trousers (black)',
				'Elf-style skirt (black)',
				'Elf-style boots (black)',
				'Elf-style shoes (black)',
				'Werewolf mask (red, male)',
				'Werewolf torso (red, male)',
				'Werewolf legs (red, male)',
				'Werewolf claws (red, male)',
				'Werewolf paws (red, male)',
				'Ikuchi orokami mask',
				'Kodama orokami mask',
				'Akkorokamui orokami mask',
				'Karasu orokami mask',
				'Akateko orokami mask',
				'Nue orokami mask',
				'Shinigami orokami mask',
				'Oni orokami mask',
				"Shaman's headdress",
				"Shaman's leggings",
				"Shaman's moccasins",
				"Shaman's poncho",
				"Shaman's hand wraps",
				'Fang of Mohegan',
				'Round glasses',
				'Stylish glasses',
				'Pyjama slippers',
				'Pyjama top',
				'Pyjama bottoms',
				'Tuxedo jacket',
				'Tuxedo trousers',
				'Tuxedo shoes',
				'Tuxedo gloves',
				'Tuxedo cravat',
				'Evening bolero',
				'Evening dipped skirt',
				'Evening gloves',
				'Evening boots',
				'Evening masquerade mask'
			].map(i),
			lvl: 40
		},
		{ item: i('Spotted cape'), lvl: 40 },
		{ item: i('Lumberjack boots'), lvl: 44 },
		{ item: i('Lumberjack hat'), lvl: 44 },
		{ item: i('Lumberjack legs'), lvl: 44 },
		{ item: i('Lumberjack top'), lvl: 44 },
		{ item: i('Spottier cape'), lvl: 66 },
		{
			item: [
				'Master farmer boots',
				'Master farmer gloves',
				'Master farmer hat',
				'Master farmer jacket',
				'Master farmer pants',
				'Mining master cape',
				'Smithing master cape',
				'Woodcutting master cape',
				'Firemaking master cape',
				'Agility master cape',
				'Fishing master cape',
				'Runecraft master cape',
				'Cooking master cape',
				'Crafting master cape',
				'Prayer master cape',
				'Fletching master cape',
				'Thieving master cape',
				'Farming master cape',
				'Herblore master cape',
				'Hunter master cape',
				'Construction master cape',
				'Magic master cape',
				'Attack master cape',
				'Strength master cape',
				'Defence master cape',
				'Ranged master cape',
				'Hitpoints master cape',
				'Slayer master cape',
				'Dungeoneering master cape',
				'Invention master cape'
			].map(i),
			lvl: 99
		}
	],
	parts: { simple: 35, protective: 5 }
};
