import getOSItem from '../../util/getOSItem';
import { DisassemblySourceGroup } from '..';

const i = getOSItem;

export const Food: DisassemblySourceGroup = {
	name: 'Food',
	items: [
		{ item: i('Apple mush'), lvl: 1 },
		{ item: i('Barley malt'), lvl: 1 },
		{ item: i('Bat shish'), lvl: 1 },
		{ item: i('Bowl of water'), lvl: 1 },
		{ item: i('Brandy'), lvl: 1 },
		{ item: i('Bread'), lvl: 1 },
		{ item: i('Bread dough'), lvl: 1 },
		{ item: i('Cheese'), lvl: 1 },
		{ item: i('Chopped onion'), lvl: 1 },
		{ item: i('Chopped tomato'), lvl: 1 },
		{ item: i("Coated frogs' legs"), lvl: 1 },
		{ item: i('Coconut shell'), lvl: 1 },
		{ item: i('Cooked chicken'), lvl: 1 },
		{ item: i('Cooked meat'), lvl: 1 },
		{ item: i('Cooked rabbit'), lvl: 1 },
		{ item: i('Cooked sweetcorn'), lvl: 1 },
		{ item: i('Crushed nest'), lvl: 1 },
		{ item: i('Edible seaweed'), lvl: 1 },
		{ item: i('Equa leaves'), lvl: 1 },
		{ item: i('Eye of newt'), lvl: 1 },
		{ item: i('Fingers'), lvl: 1 },
		{ item: i('Flax'), lvl: 1 },
		{ item: i('Fresh monkfish'), lvl: 1 },
		{ item: i('Frogburger'), lvl: 1 },
		{ item: i('Frogspawn gumbo'), lvl: 1 },
		{ item: i('Gin'), lvl: 1 },
		{ item: i('Green gloop soup'), lvl: 1 },
		{ item: i("Grimy rogue's purse"), lvl: 1 },
		{ item: i('Grimy sito foil'), lvl: 1 },
		{ item: i('Grimy snake weed'), lvl: 1 },
		{ item: i('Grimy volencia moss'), lvl: 1 },
		{ item: i('Karambwanji'), lvl: 1 },
		{ item: i('King worm'), lvl: 1 },
		{ item: i('Leaves'), lvl: 1 },
		{ item: i('Lemon'), lvl: 1 },
		{ item: i('Lemon chunks'), lvl: 1 },
		{ item: i('Lemon slices'), lvl: 1 },
		{ item: i('Lime'), lvl: 1 },
		{ item: i('Lime chunks'), lvl: 1 },
		{ item: i('Lime slices'), lvl: 1 },
		{ item: i('Magic roots'), lvl: 1 },
		{ item: i('Mangled bones'), lvl: 1 },
		{ item: i('Maple roots'), lvl: 1 },
		{ item: i('Minnow'), lvl: 1 },
		{ item: i('Oak roots'), lvl: 1 },
		{ item: i('Orange chunks'), lvl: 1 },
		{ item: i('Orange slices'), lvl: 1 },
		{ item: i('Pineapple chunks'), lvl: 1 },
		{ item: i('Pineapple ring'), lvl: 1 },
		{ item: i('Pot of cream'), lvl: 1 },
		{ item: i('Purple sweets'), lvl: 1 },
		{ item: i('Raw anchovies'), lvl: 1 },
		{ item: i('Raw bear meat'), lvl: 1 },
		{ item: i('Raw beast meat'), lvl: 1 },
		{ item: i('Raw beef'), lvl: 1 },
		{ item: i('Raw bird meat'), lvl: 1 },
		{ item: i('Raw chicken'), lvl: 1 },
		{ item: i('Raw karambwan'), lvl: 1 },
		{ item: i('Raw karambwanji'), lvl: 1 },
		{ item: i('Raw rabbit'), lvl: 1 },
		{ item: i('Raw rat meat'), lvl: 1 },
		{ item: i('Raw sardine'), lvl: 1 },
		{ item: i('Raw shrimps'), lvl: 1 },
		{ item: i('Raw swamp paste'), lvl: 1 },
		{ item: i('Raw ugthanki meat'), lvl: 1 },
		{ item: i('Raw yak meat'), lvl: 1 },
		{ item: i("Red spiders' eggs"), lvl: 1 },
		{ item: i('Roast bird meat'), lvl: 1 },
		{ item: i('Rotten apple'), lvl: 1 },
		{ item: i('Sardine'), lvl: 1 },
		{ item: i('Seaweed'), lvl: 1 },
		{ item: i('Shrimps'), lvl: 1 },
		{ item: i('Sliced banana'), lvl: 1 },
		{ item: i('Spicy tomato'), lvl: 1 },
		{ item: i('Spinach roll'), lvl: 1 },
		{ item: i('Swamp weed'), lvl: 1 },
		{ item: i('Tenti pineapple'), lvl: 1 },
		{ item: i('Ugthanki meat'), lvl: 1 },
		{ item: i('Vodka'), lvl: 1 },
		{ item: i('Watermelon slice'), lvl: 1 },
		{ item: i('Weeds'), lvl: 1 },
		{ item: i('Whisky'), lvl: 1 },
		{ item: i('White pearl'), lvl: 1 },
		{ item: i('Willow branch'), lvl: 1 },
		{ item: i('Willow roots'), lvl: 1 },
		{ item: i('Yew roots'), lvl: 1 },
		{ item: i('Marigolds'), lvl: 2 },
		{ item: i('Barley'), lvl: 3 },
		{ item: i('Chocolate bar'), lvl: 3 },
		{ item: i('Kebab'), lvl: 3 },
		{ item: i('Locust meat'), lvl: 3 },
		{ item: i('Spicy minced meat'), lvl: 3 },
		{ item: i("Toad's legs"), lvl: 3 },
		{ item: i('Chocolatey milk'), lvl: 4 },
		{ item: i('Hammerstone hops'), lvl: 4 },
		{ item: i('Super kebab'), lvl: 4 },
		{ item: i('Grimy tarromin'), lvl: 5 },
		{ item: i('Herring'), lvl: 5 },
		{ item: i('Monkey nuts'), lvl: 5 },
		{ item: i('Onion'), lvl: 5 },
		{ item: i('Raw herring'), lvl: 5 },
		{ item: i('Fruit blast'), lvl: 6 },
		{ item: i('Baked potato'), lvl: 7 },
		{
			item: i('Cabbage'),
			lvl: 7,
			special: { always: false, parts: [{ type: 'brassican', chance: 100, amount: 1 }] }
		},
		{ item: i('Red banana'), lvl: 7 },
		{ item: i('Sliced red banana'), lvl: 7 },
		{ item: i('Tchiki monkey nuts'), lvl: 7 },
		{ item: i('Tchiki nut paste'), lvl: 7 },
		{ item: i('Asgarnian hops'), lvl: 8 },
		{ item: i('Pineapple punch'), lvl: 8 },
		{ item: i('Grimy marrentill'), lvl: 9 },
		{ item: i('Minced meat'), lvl: 9 },
		{ item: i('Spicy sauce'), lvl: 9 },
		{ item: i('Baguette'), lvl: 10 },
		{ item: i('Beer'), lvl: 10 },
		{ item: i('Beer tankard'), lvl: 10 },
		{ item: i('Compost'), lvl: 10 },
		{ item: i('Eel sushi'), lvl: 10 },
		{ item: i('Fillets'), lvl: 10 },
		{ item: i('Frog spawn'), lvl: 10 },
		{ item: i('Giant carp'), lvl: 10 },
		{ item: i('Giant frog legs'), lvl: 10 },
		{ item: i('Grog'), lvl: 10 },
		{ item: i('Grubs à la mode'), lvl: 10 },
		{ item: i('Keg of beer'), lvl: 10 },
		{ item: i('Loach'), lvl: 10 },
		{ item: i('Mackerel'), lvl: 10 },
		{ item: i('Mushrooms'), lvl: 10 },
		{ item: i('Raw giant carp'), lvl: 10 },
		{ item: i('Raw mackerel'), lvl: 10 },
		{ item: i('Redberries'), lvl: 10 },
		{ item: i('Redberry pie'), lvl: 10 },
		{ item: i('Roast frog'), lvl: 10 },
		{ item: i('Roll'), lvl: 10 },
		{ item: i('Rosemary'), lvl: 10 },
		{ item: i('Square sandwich'), lvl: 10 },
		{ item: i('Triangle sandwich'), lvl: 10 },
		{ item: i('Uncooked berry pie'), lvl: 10 },
		{ item: i('White tree fruit'), lvl: 10 },
		{ item: i('Chilli con carne'), lvl: 11 },
		{ item: i('Skewered bird meat'), lvl: 11 },
		{ item: i('Roe'), lvl: 12 },
		{ item: i('Thin snail'), lvl: 12 },
		{ item: i('Thin snail meat'), lvl: 12 },
		{ item: i('Tomato'), lvl: 12 },
		{ item: i('Scrambled egg'), lvl: 13 },
		{ item: i('Uncooked egg'), lvl: 13 },
		{ item: i('Cave nightshade'), lvl: 14 },
		{ item: i('Cider'), lvl: 14 },
		{ item: i('Choc-ice'), lvl: 15 },
		{ item: i('Chocchip crunchies'), lvl: 15 },
		{ item: i('Cup of tea'), lvl: 15 },
		{ item: i('Raw trout'), lvl: 15 },
		{ item: i('Spicy crunchies'), lvl: 15 },
		{ item: i('Tea flask'), lvl: 15 },
		{ item: i('Trout'), lvl: 15 },
		{ item: i('Roast rabbit'), lvl: 16 },
		{ item: i('Skewered rabbit'), lvl: 16 },
		{ item: i('Spider on shaft'), lvl: 16 },
		{ item: i('Spider on stick'), lvl: 16 },
		{ item: i('Yanillian hops'), lvl: 16 },
		{ item: i('Kelda hops'), lvl: 17 },
		{ item: i('Lean snail'), lvl: 17 },
		{ item: i('Lean snail meat'), lvl: 17 },
		{ item: i('Mature cider'), lvl: 17 },
		{ item: i('Cod'), lvl: 18 },
		{ item: i('Raw cod'), lvl: 18 },
		{ item: i('Wizard blizzard'), lvl: 18 },
		{ item: i('Dwarven stout'), lvl: 19 },
		{ item: i('Apple pie'), lvl: 20 },
		{ item: i('Grimy harralander'), lvl: 20 },
		{ item: i('Meat pie'), lvl: 20 },
		{ item: i('Nettle tea'), lvl: 20 },
		{ item: i('Nettle-water'), lvl: 20 },
		{ item: i('Peach'), lvl: 20 },
		{ item: i('Pike'), lvl: 20 },
		{ item: i('Raw pike'), lvl: 20 },
		{ item: i('Short green guy'), lvl: 20 },
		{ item: i('Supercompost'), lvl: 20 },
		{ item: i('Sweetcorn'), lvl: 20 },
		{ item: i('Toad crunchies'), lvl: 20 },
		{ item: i('Uncooked meat pie'), lvl: 20 },
		{ item: i('Worm crunchies'), lvl: 20 },
		{ item: i('Cooked crab meat'), lvl: 21 },
		{ item: i('Crab meat'), lvl: 21 },
		{ item: i('Krandorian hops'), lvl: 21 },
		{ item: i('Roast beast meat'), lvl: 21 },
		{ item: i('Skewered beast'), lvl: 21 },
		{ item: i('Cadava berries'), lvl: 22 },
		{ item: i('Dwarven stout(m)'), lvl: 22 },
		{ item: i('Fat snail'), lvl: 22 },
		{ item: i('Fat snail meat'), lvl: 22 },
		{ item: i('Egg and tomato'), lvl: 23 },
		{ item: i('Asgarnian ale'), lvl: 24 },
		{ item: i('Caviar'), lvl: 24 },
		{ item: i('Karamjan rum'), lvl: 25 },
		{ item: i('Monkey bar'), lvl: 25 },
		{ item: i('Raw salmon'), lvl: 25 },
		{ item: i('Salmon'), lvl: 25 },
		{ item: i('Stew'), lvl: 25 },
		{ item: i('Uncooked stew'), lvl: 25 },
		{ item: i('Woad leaf'), lvl: 25 },
		{ item: i('Limpwurt root'), lvl: 26 },
		{ item: i('Asgarnian ale(m)'), lvl: 27 },
		{ item: i('Cooking apple'), lvl: 27 },
		{ item: i('Cooked slimy eel'), lvl: 28 },
		{ item: i('Wildblood hops'), lvl: 28 },
		{ item: i("Greenman's ale"), lvl: 29 },
		{ item: i('Mud pie'), lvl: 29 },
		{ item: i('Raw mud pie'), lvl: 29 },
		{ item: i('Chopped tuna'), lvl: 30 },
		{ item: i('Cooked chompy'), lvl: 30 },
		{ item: i('Cooked karambwan'), lvl: 30 },
		{ item: i('Grimy toadflax'), lvl: 30 },
		{ item: i('Raw tuna'), lvl: 30 },
		{ item: i('Skewered chompy'), lvl: 30 },
		{ item: i('Snape grass'), lvl: 30 },
		{ item: i('Tuna'), lvl: 30 },
		{ item: i('Ultracompost'), lvl: 30 },
		{ item: i('Uncooked apple pie'), lvl: 30 },
		{ item: i('Raw fishcake'), lvl: 31 },
		{ item: i('Strawberry'), lvl: 31 },
		{ item: i('Drunk dragon'), lvl: 32 },
		{ item: i("Greenman's ale(m)"), lvl: 32 },
		{ item: i('Banana'), lvl: 33 },
		{ item: i('Garden pie'), lvl: 34 },
		{ item: i('Raw garden pie'), lvl: 34 },
		{ item: i("Wizard's mind bomb"), lvl: 34 },
		{ item: i('Banana stew'), lvl: 35 },
		{ item: i('Cheese+tom batta'), lvl: 35 },
		{ item: i('Cooked fishcake'), lvl: 35 },
		{ item: i('Fruit batta'), lvl: 35 },
		{ item: i('Jug of wine'), lvl: 35 },
		{ item: i('Plain pizza'), lvl: 35 },
		{ item: i('Premade c+t batta'), lvl: 35 },
		{ item: i('Premade veg batta'), lvl: 35 },
		{ item: i('Rainbow fish'), lvl: 35 },
		{ item: i('Raw rainbow fish'), lvl: 35 },
		{ item: i('Spicy stew'), lvl: 35 },
		{ item: i('Toad batta'), lvl: 35 },
		{ item: i('Uncooked pizza'), lvl: 35 },
		{ item: i('Vegetable batta'), lvl: 35 },
		{ item: i('Witchwood icon'), lvl: 35 },
		{ item: i('Worm batta'), lvl: 35 },
		{ item: i('Dwellberries'), lvl: 36 },
		{ item: i('Blurberry special'), lvl: 37 },
		{ item: i('Cave eel'), lvl: 38 },
		{ item: i('Raw cave eel'), lvl: 38 },
		{ item: i('Dragon bitter'), lvl: 39 },
		{ item: i('Orange'), lvl: 39 },
		{ item: i('Potato with butter'), lvl: 39 },
		{ item: i('Cake'), lvl: 40 },
		{ item: i('Premade veg ball'), lvl: 40 },
		{ item: i('Premade worm hole'), lvl: 40 },
		{ item: i('Raw guide cake'), lvl: 40 },
		{ item: i('Raw lobster'), lvl: 40 },
		{ item: i('Uncooked cake'), lvl: 40 },
		{ item: i('Veg ball'), lvl: 40 },
		{ item: i('Worm hole'), lvl: 40 },
		{ item: i('Cooked jubbly'), lvl: 41 },
		{ item: i('Raw jubbly'), lvl: 41 },
		{ item: i('Curry leaf'), lvl: 42 },
		{ item: i('Dragon bitter(m)'), lvl: 42 },
		{ item: i('Fried onions'), lvl: 42 },
		{ item: i('Big bass'), lvl: 43 },
		{ item: i('Raw bass'), lvl: 43 },
		{ item: i('Moonlight mead'), lvl: 44 },
		{ item: i('Big swordfish'), lvl: 45 },
		{ item: i('Cooked oomlie wrap'), lvl: 45 },
		{ item: i('Meat pizza'), lvl: 45 },
		{ item: i('Raw swordfish'), lvl: 45 },
		{ item: i('Fried mushrooms'), lvl: 46 },
		{ item: i('Sliced mushrooms'), lvl: 46 },
		{ item: i('Fish pie'), lvl: 47 },
		{ item: i('Moonlight mead(m)'), lvl: 47 },
		{ item: i('Potato with cheese'), lvl: 47 },
		{ item: i('Raw fish pie'), lvl: 47 },
		{ item: i('Watermelon'), lvl: 47 },
		{ item: i('Grimy avantoe'), lvl: 48 },
		{ item: i('Jangerberries'), lvl: 48 },
		{ item: i('Lobster'), lvl: 48 },
		{ item: i("Axeman's folly"), lvl: 49 },
		{ item: i("Braindeath 'rum'"), lvl: 50 },
		{ item: i('Chilli potato'), lvl: 50 },
		{ item: i('Chocolate cake'), lvl: 50 },
		{ item: i('Wrapped oomlie'), lvl: 50 },
		{ item: i('Pineapple'), lvl: 51 },
		{ item: i("Axeman's folly(m)"), lvl: 52 },
		{ item: i('Bass'), lvl: 52 },
		{ item: i('Lava eel'), lvl: 53 },
		{ item: i('Raw lava eel'), lvl: 53 },
		{ item: i("Chef's delight"), lvl: 54 },
		{ item: i('Grimy kwuarm'), lvl: 54 },
		{ item: i('Egg potato'), lvl: 55 },
		{ item: i('Swordfish'), lvl: 56 },
		{ item: i("Chef's delight(m)"), lvl: 57 },
		{ item: i('Papaya fruit'), lvl: 57 },
		{ item: i('Pitta dough'), lvl: 58 },
		{ item: i('Grimy snapdragon'), lvl: 59 },
		{ item: i("Slayer's respite"), lvl: 59 },
		{ item: i('White berries'), lvl: 59 },
		{ item: i('Bottle of wine'), lvl: 60 },
		{ item: i('Catfish'), lvl: 60 },
		{ item: i('Chocolate bomb'), lvl: 60 },
		{ item: i('Curry'), lvl: 60 },
		{ item: i('Premade choc bomb'), lvl: 60 },
		{ item: i('Premade ttl'), lvl: 60 },
		{ item: i('Raw catfish'), lvl: 60 },
		{ item: i("Tangled toad's legs"), lvl: 60 },
		{ item: i('Uncooked curry'), lvl: 60 },
		{ item: i('Raw monkfish'), lvl: 62 },
		{ item: i("Slayer's respite(m)"), lvl: 62 },
		{ item: i('Monkfish'), lvl: 64 },
		{ item: i('Grimy cadantine'), lvl: 65 },
		{ item: i('Pineapple pizza'), lvl: 65 },
		{ item: i('Grimy lantadyme'), lvl: 67 },
		{ item: i('Tuna and corn'), lvl: 67 },
		{ item: i('Coconut'), lvl: 68 },
		{ item: i('Grimy dwarf weed'), lvl: 70 },
		{ item: i('Poison ivy berries'), lvl: 70 },
		{ item: i('Raw admiral pie'), lvl: 70 },
		{ item: i('Ugthanki kebab'), lvl: 70 },
		{ item: i('Calquat fruit'), lvl: 72 },
		{ item: i('Grimy torstol'), lvl: 75 },
		{ item: i('Big shark'), lvl: 80 },
		{ item: i('Mushroom potato'), lvl: 80 },
		{ item: i('Raw shark'), lvl: 80 },
		{ item: i('Shark'), lvl: 80 },
		{ item: i('Stuffed snake'), lvl: 80 },
		{ item: i('Raw sea turtle'), lvl: 82 },
		{ item: i('Sea turtle'), lvl: 82 },
		{ item: i('Raw wild pie'), lvl: 85 },
		{ item: i('Tuna potato'), lvl: 85 },
		{ item: i('Wild pie'), lvl: 85 },
		{ item: i('Potato cactus'), lvl: 86 },
		{ item: i('Cavefish'), lvl: 88 },
		{ item: i('Raw cavefish'), lvl: 88 },
		{ item: i('Manta ray'), lvl: 91 },
		{ item: i('Raw manta ray'), lvl: 91 },
		{ item: i('Dragonfruit'), lvl: 95 },
		{ item: i('Raw summer pie'), lvl: 95 },
		{ item: i('Summer pie'), lvl: 95 }
	],
	parts: { healthy: 1, enhancing: 1, living: 1, crafted: 8, organic: 89 },
	partQuantity: 1
};

export default Food;
