import type { DisassemblySourceGroup } from '..';
import getOSItem from '../../util/getOSItem';

const i = getOSItem;

export const Organic: DisassemblySourceGroup = {
	name: 'Organic',
	items: [
		// Seeds
		{ item: i('Potato seed'), lvl: 1 },
		{ item: i('Marigold seed'), lvl: 2 },
		{ item: i('Barley seed'), lvl: 3 },
		{ item: i('Hammerstone seed'), lvl: 4 },
		{ item: i('Onion seed'), lvl: 5 },
		{ item: i('Cabbage seed'), lvl: 7 },
		{ item: i('Asgarnian seed'), lvl: 8 },
		{ item: i('Guam seed'), lvl: 9 },
		{ item: i('Delphinium seed'), lvl: 10 },
		{ item: i('Pink rose seed'), lvl: 10 },
		{ item: i('Red rose seed'), lvl: 10 },
		{ item: i('Redberry seed'), lvl: 10 },
		{ item: i('Snowdrop seed'), lvl: 10 },
		{ item: i('Vine seed'), lvl: 10 },
		{ item: i('White rose seed'), lvl: 10 },
		{ item: i('Rosemary seed'), lvl: 11 },
		{ item: i('Tomato seed'), lvl: 12 },
		{ item: i('Jute seed'), lvl: 13 },
		{ item: i('Marrentill seed'), lvl: 14 },
		{ item: i('Yanillian seed'), lvl: 16 },
		{ item: i('Kelda seed'), lvl: 17 },
		{ item: i('Tarromin seed'), lvl: 19 },
		{ item: i('Sweetcorn seed'), lvl: 20 },
		{ item: i('Krandorian seed'), lvl: 21 },
		{ item: i('Cadavaberry seed'), lvl: 22 },
		{ item: i('Nasturtium seed'), lvl: 24 },
		{ item: i('White tree shoot'), lvl: 25 },
		{ item: i('Woad seed'), lvl: 25 },
		{ item: i('Harralander seed'), lvl: 26 },
		{ item: i('Limpwurt seed'), lvl: 26 },
		{ item: i('Apple tree seed'), lvl: 27 },
		{ item: i('Wildblood seed'), lvl: 28 },
		{ item: i('Gout tuber'), lvl: 29 },
		{ item: i('Willow seed'), lvl: 30 },
		{ item: i('Strawberry seed'), lvl: 31 },
		{ item: i('Ranarr seed'), lvl: 32 },
		{ item: i('Banana tree seed'), lvl: 33 },
		{ item: i('Teak seed'), lvl: 35 },
		{ item: i('Dwellberry seed'), lvl: 36 },
		{ item: i('Toadflax seed'), lvl: 38 },
		{ item: i('Orange tree seed'), lvl: 39 },
		{ item: i('Blindweed seed'), lvl: 40 },
		{ item: i('Curry tree seed'), lvl: 42 },
		{ item: i('Irit seed'), lvl: 44 },
		{ item: i('Maple seed'), lvl: 45 },
		{ item: i('Watermelon seed'), lvl: 47 },
		{ item: i('Jangerberry seed'), lvl: 48 },
		{ item: i('Avantoe seed'), lvl: 50 },
		{ item: i('Pineapple seed'), lvl: 51 },
		{ item: i('White lily seed'), lvl: 52 },
		{ item: i('Mahogany seed'), lvl: 55 },
		{ item: i('Cactus seed'), lvl: 55 },
		{ item: i('Kwuarm seed'), lvl: 56 },
		{ item: i('Papaya tree seed'), lvl: 57 },
		{ item: i('Whiteberry seed'), lvl: 59 },
		{ item: i('Yew seed'), lvl: 60 },
		{ item: i('Snapdragon seed'), lvl: 62 },
		{ item: i('Belladonna seed'), lvl: 63 },
		{ item: i('Cadantine seed'), lvl: 67 },
		{ item: i('Palm tree seed'), lvl: 68 },
		{ item: i('Grape seed'), lvl: 68 },
		{ item: i('Poison ivy seed'), lvl: 70 },
		{ item: i('Calquat tree seed'), lvl: 72 },
		{ item: i('Lantadyme seed'), lvl: 73 },
		{ item: i('Magic seed'), lvl: 75 },
		{ item: i('Dwarf weed seed'), lvl: 79 },
		{ item: i('Snape grass seed'), lvl: 80 },
		{ item: i('Dragonfruit tree seed'), lvl: 80 },
		{ item: i('Spirit seed'), lvl: 83 },
		{ item: i('Torstol seed'), lvl: 85 },
		{ item: i('Potato cactus seed'), lvl: 86 },
		{ item: i('Avocado seed'), lvl: 99 },
		{ item: i('Athelas seed'), lvl: 99 },
		{ item: i('Mango seed'), lvl: 90 },
		{ item: i('Lychee seed'), lvl: 90 },
		{ item: i('Mysterious seed'), lvl: 99 },
		// Misc
		{
			item: [
				'Cheese',
				'Apple pie',
				'Raw turkey',
				'Premade choc bomb',
				'Dragon bitter',
				'Cooked chompy',
				'Cooked crab meat',
				'Cooked jubbly',
				'Cooked meat',
				'Cooked mystery meat',
				'Cooked oomlie wrap',
				'Cooked rabbit',
				'Cooked slimy eel',
				'Cooked sweetcorn',
				'Cooking apple',
				'Dragon bitter',
				'Dragon bitter(4)',
				'Dragon bitter(m)',
				'Curry leaf',
				'Dragon bitter(m4)',
				'Raw yak meat',
				'Redberries',
				'Dwellberries',
				'Desert goat horn',
				'Vegetable batta',
				'Fat snail',
				'Bacon',
				"Premade fr't batta",
				'Raw oomlie',
				'Pineapple chunks',
				'Pineapple pizza',
				'Pineapple punch',
				'Pineapple ring',
				'Pineapple sapling',
				'Raw admiral pie',
				'Raw bear meat',
				'Raw beast meat',
				'Raw boar meat',
				'Raw cave eel',
				'Raw chompy',
				'Raw garden pie',
				'Raw jubbly',
				'Raw mud pie',
				'Raw mystery meat',
				'Raw rainbow fish',
				'Raw slimy eel',
				'Raw ugthanki meat',
				'Spicy crunchies',
				'Spicy minced meat',
				'Spicy sauce',
				'Spicy tomato',
				'Spider carcass',
				'Spider on shaft',
				'Spider on stick',
				'Spinach roll',
				'Rainbow fish',
				'Sliced mushrooms',
				'Uncooked apple pie',
				'Uncooked berry pie',
				'Uncooked botanical pie',
				'Uncooked dragonfruit pie',
				'Uncooked egg',
				'Uncooked meat pie',
				'Uncooked mushroom pie',
				'Scrambled egg',
				'Wool',
				'Worm batta',
				'Worm crunchies',
				'Worm hole',
				'Wrapped oomlie',
				"Premade blurb' sp.",
				'Premade c+t batta',
				"Premade ch' crunch",
				"Premade choc s'dy",
				"Premade dr' dragon",
				"Premade fr' blast",
				"Premade p' punch",
				"Premade s'y crunch",
				'Premade sgg',
				"Premade t'd batta",
				"Premade t'd crunch",
				'Premade ttl',
				'Premade veg ball',
				'Premade veg batta',
				"Premade w'm batta",
				"Premade w'm crun'",
				"Premade wiz blz'd",
				'Premade worm hole',
				'Garden pie',
				'Pretzel',
				'Pot of cornflour',
				'Pot of cream',
				'Pot of flour',
				'Potato',
				'Potato with butter',
				'Egg',
				'Egg and tomato',
				'Egg potato',
				'Chocchip crunchies',
				'Chocolate bar',
				'Chocolate bomb',
				'Chocolate dust',
				'Chocolified skull',
				'Chopped garlic',
				'Woad leaf',
				'Chopped onion',
				'Yellow flowers',
				'Yanillian hops',
				'Fish chunks',
				'Fish food',
				'Fish n chips',
				'Fish offcuts',
				'Chopped tomato',
				'Chopped tuna',
				'Chopped ugthanki',
				'Choc saturday',
				"Choc'rock",
				'Choc-ice',
				'Burnt turkey',
				'Chilli con carne',
				'Chilli potato',
				'Anchovies',
				'Anchovy pizza',
				'Whisky',
				'Weeds'
			].map(i),
			lvl: 1
		},
		{ item: i('Yew roots'), lvl: 35 },
		{ item: i('Magic roots'), lvl: 55 },
		{ item: i('Limpwurt root'), lvl: 35 },
		{ item: i('Giant seaweed'), lvl: 45 },
		{ item: i("Red spiders' eggs"), lvl: 45 },
		{ item: i('Potato cactus'), lvl: 55 },
		{ item: i('Mort myre fungus'), lvl: 55 },
		{ item: i("Zulrah's scales"), lvl: 55 },
		{ item: i('Black salamander'), lvl: 70 },
		{ item: i('Chimpchompa'), lvl: 70 },
		{ item: i('Big banana'), lvl: 70 },
		{ item: i('Ignecarus scales'), lvl: 85 },
		{ item: i('Simple kibble'), lvl: 90 },
		{ item: i('Avocado'), lvl: 90 },
		{ item: i('Mango'), lvl: 90 },
		{ item: i('Lychee'), lvl: 90 },
		{ item: i('Delicious kibble'), lvl: 95 },
		{ item: ['Extraordinary kibble', 'Ignecarus dragonclaw', 'Dragon egg'].map(i), lvl: 99 }
	],
	parts: { organic: 100 }
};
