import getOSItem from '../../util/getOSItem';
import { DisassemblySourceGroup } from '..';

const i = getOSItem;

export const Potion: DisassemblySourceGroup = {
	name: 'Potion',
	items: [
		{ item: i('Attack potion(2)'), lvl: 1 },
		{ item: i('Attack potion(4)'), lvl: 1 },
		{ item: i('Attack potion(3)'), lvl: 1 },
		{ item: i('Attack potion(1)'), lvl: 1 },
		{ item: i('Ranging potion(2)'), lvl: 3 },
		{ item: i('Ranging potion(4)'), lvl: 3 },
		{ item: i('Ranging potion(3)'), lvl: 3 },
		{ item: i('Ranging potion(1)'), lvl: 3 },
		{ item: i('Magic potion(2)'), lvl: 5 },
		{ item: i('Magic potion(4)'), lvl: 5 },
		{ item: i('Magic potion(3)'), lvl: 5 },
		{ item: i('Magic potion(1)'), lvl: 5 },
		{ item: i('Strength potion(2)'), lvl: 7 },
		{ item: i('Strength potion(4)'), lvl: 7 },
		{ item: i('Strength potion(3)'), lvl: 7 },
		{ item: i('Strength potion(1)'), lvl: 7 },
		{ item: i("Relicym's balm(2)"), lvl: 8 },
		{ item: i("Relicym's balm(4)"), lvl: 8 },
		{ item: i("Relicym's balm(3)"), lvl: 8 },
		{ item: i("Relicym's balm(1)"), lvl: 8 },
		{ item: i('Defence potion(2)'), lvl: 9 },
		{ item: i('Defence potion(4)'), lvl: 9 },
		{ item: i('Defence potion(3)'), lvl: 9 },
		{ item: i('Defence potion(1)'), lvl: 9 },
		{ item: i('Guthix rest(2)'), lvl: 18 },
		{ item: i('Guthix rest(4)'), lvl: 18 },
		{ item: i('Guthix rest(3)'), lvl: 18 },
		{ item: i('Guthix rest(1)'), lvl: 18 },
		{ item: i('Guthix balance(2)'), lvl: 22 },
		{ item: i('Guthix balance(4)'), lvl: 22 },
		{ item: i('Guthix balance(3)'), lvl: 22 },
		{ item: i('Guthix balance(1)'), lvl: 22 },
		{ item: i('Restore potion(2)'), lvl: 22 },
		{ item: i('Restore potion(4)'), lvl: 22 },
		{ item: i('Restore potion(3)'), lvl: 22 },
		{ item: i('Restore potion(1)'), lvl: 22 },
		{ item: i('Energy potion(2)'), lvl: 26 },
		{ item: i('Energy potion(4)'), lvl: 26 },
		{ item: i('Energy potion(3)'), lvl: 26 },
		{ item: i('Energy potion(1)'), lvl: 26 },
		{ item: i('Combat potion(2)'), lvl: 36 },
		{ item: i('Combat potion(4)'), lvl: 36 },
		{ item: i('Combat potion(3)'), lvl: 36 },
		{ item: i('Combat potion(1)'), lvl: 36 },
		{ item: i('Prayer potion(2)'), lvl: 38 },
		{ item: i('Prayer potion(4)'), lvl: 38 },
		{ item: i('Prayer potion(3)'), lvl: 38 },
		{ item: i('Prayer potion(1)'), lvl: 38 },
		{ item: i('Super attack(2)'), lvl: 45 },
		{ item: i('Super attack(4)'), lvl: 45 },
		{ item: i('Super attack(3)'), lvl: 45 },
		{ item: i('Super attack(1)'), lvl: 45 },
		{ item: i('Superantipoison(2)'), lvl: 48 },
		{ item: i('Superantipoison(4)'), lvl: 48 },
		{ item: i('Superantipoison(3)'), lvl: 48 },
		{ item: i('Superantipoison(1)'), lvl: 48 },
		{ item: i('Fishing potion(2)'), lvl: 50 },
		{ item: i('Fishing potion(4)'), lvl: 50 },
		{ item: i('Fishing potion(3)'), lvl: 50 },
		{ item: i('Fishing potion(1)'), lvl: 50 },
		{ item: i('Super energy(2)'), lvl: 52 },
		{ item: i('Super energy(4)'), lvl: 52 },
		{ item: i('Super energy(3)'), lvl: 52 },
		{ item: i('Super energy(1)'), lvl: 52 },
		{ item: i('Hunter potion(2)'), lvl: 53 },
		{ item: i('Hunter potion(4)'), lvl: 53 },
		{ item: i('Hunter potion(3)'), lvl: 53 },
		{ item: i('Hunter potion(1)'), lvl: 53 },
		{ item: i('Super strength(2)'), lvl: 55 },
		{ item: i('Super strength(4)'), lvl: 55 },
		{ item: i('Super strength(3)'), lvl: 55 },
		{ item: i('Super strength(1)'), lvl: 55 },
		{ item: i('Magic essence(2)'), lvl: 57 },
		{ item: i('Magic essence(4)'), lvl: 57 },
		{ item: i('Magic essence(3)'), lvl: 57 },
		{ item: i('Magic essence(1)'), lvl: 57 },
		{ item: i('Magic essence (unf)'), lvl: 57 },
		{ item: i('Super restore(2)'), lvl: 63 },
		{ item: i('Super restore(4)'), lvl: 63 },
		{ item: i('Super restore(3)'), lvl: 63 },
		{ item: i('Super restore(1)'), lvl: 63 },
		{ item: i('Sanfew serum(2)'), lvl: 65 },
		{ item: i('Sanfew serum(4)'), lvl: 65 },
		{ item: i('Sanfew serum(3)'), lvl: 65 },
		{ item: i('Sanfew serum(1)'), lvl: 65 },
		{ item: i('Super defence(2)'), lvl: 66 },
		{ item: i('Super defence(4)'), lvl: 66 },
		{ item: i('Super defence(3)'), lvl: 66 },
		{ item: i('Super defence(1)'), lvl: 66 },
		{ item: i('Super magic potion (2)'), lvl: 76 },
		{ item: i('Super magic potion (4)'), lvl: 76 },
		{ item: i('Super magic potion (3)'), lvl: 76 },
		{ item: i('Super magic potion (1)'), lvl: 76 },
		{ item: i('Stamina potion(2)'), lvl: 77 },
		{ item: i('Stamina potion(4)'), lvl: 77 },
		{ item: i('Stamina potion(3)'), lvl: 77 },
		{ item: i('Stamina potion(1)'), lvl: 77 },
		{ item: i('Zamorak brew(2)'), lvl: 78 },
		{ item: i('Zamorak brew(4)'), lvl: 78 },
		{ item: i('Zamorak brew(3)'), lvl: 78 },
		{ item: i('Zamorak brew(1)'), lvl: 78 },
		{ item: i('Saradomin brew(2)'), lvl: 81 },
		{ item: i('Saradomin brew(4)'), lvl: 81 },
		{ item: i('Saradomin brew(3)'), lvl: 81 },
		{ item: i('Saradomin brew(1)'), lvl: 81 },
		{ item: i('Extended super antifire(2)'), lvl: 90 },
		{ item: i('Extended super antifire(4)'), lvl: 90 },
		{ item: i('Extended super antifire(3)'), lvl: 90 },
		{ item: i('Extended super antifire(1)'), lvl: 90 }
	],
	parts: { delicate: 35, organic: 32 }
};
