import type { DisassemblySourceGroup } from '@/lib/invention/index.js';
import getOSItem from '@/lib/util/getOSItem.js';

const i = getOSItem;

export const Potion: DisassemblySourceGroup = {
	name: 'Potion',
	items: [
		{ item: Items.getOrThrow('Attack potion (1)'), lvl: 1 },
		{ item: Items.getOrThrow('Attack potion (2)'), lvl: 2 },
		{ item: Items.getOrThrow('Attack potion (3)'), lvl: 3 },
		{ item: Items.getOrThrow('Attack potion (4)'), lvl: 3 },
		{ item: Items.getOrThrow('Antipoison (1)'), lvl: 2 },
		{ item: Items.getOrThrow('Antipoison (2)'), lvl: 3 },
		{ item: Items.getOrThrow('Antipoison (3)'), lvl: 4 },
		{ item: Items.getOrThrow('Antipoison (4)'), lvl: 5 },
		{ item: Items.getOrThrow('Strength potion (1)'), lvl: 3 },
		{ item: Items.getOrThrow('Strength potion (2)'), lvl: 6 },
		{ item: Items.getOrThrow('Strength potion (3)'), lvl: 9 },
		{ item: Items.getOrThrow('Strength potion (4)'), lvl: 12 },
		{ item: Items.getOrThrow('Serum 207 (1)'), lvl: 4 },
		{ item: Items.getOrThrow('Serum 207 (2)'), lvl: 8 },
		{ item: Items.getOrThrow('Serum 207 (3)'), lvl: 12 },
		{ item: Items.getOrThrow('Serum 207 (4)'), lvl: 15 },
		{ item: Items.getOrThrow('Compost potion (1)'), lvl: 6 },
		{ item: Items.getOrThrow('Compost potion (2)'), lvl: 11 },
		{ item: Items.getOrThrow('Compost potion (3)'), lvl: 17 },
		{ item: Items.getOrThrow('Compost potion (4)'), lvl: 22 },
		{ item: Items.getOrThrow('Restore potion (1)'), lvl: 6 },
		{ item: Items.getOrThrow('Restore potion (2)'), lvl: 11 },
		{ item: Items.getOrThrow('Restore potion (3)'), lvl: 17 },
		{ item: Items.getOrThrow('Restore potion (4)'), lvl: 22 },
		{ item: Items.getOrThrow('Guthix balance (1)'), lvl: 6 },
		{ item: Items.getOrThrow('Guthix balance (2)'), lvl: 11 },
		{ item: Items.getOrThrow('Guthix balance (3)'), lvl: 17 },
		{ item: Items.getOrThrow('Guthix balance (4)'), lvl: 22 },
		{ item: Items.getOrThrow('Energy potion (1)'), lvl: 7 },
		{ item: Items.getOrThrow('Energy potion (2)'), lvl: 13 },
		{ item: Items.getOrThrow('Energy potion (3)'), lvl: 20 },
		{ item: Items.getOrThrow('Energy potion (4)'), lvl: 26 },
		{ item: Items.getOrThrow('Defence potion (1)'), lvl: 8 },
		{ item: Items.getOrThrow('Defence potion (2)'), lvl: 15 },
		{ item: Items.getOrThrow('Defence potion (3)'), lvl: 23 },
		{ item: Items.getOrThrow('Defence potion (4)'), lvl: 30 },
		{ item: Items.getOrThrow('Agility potion (1)'), lvl: 9 },
		{ item: Items.getOrThrow('Agility potion (2)'), lvl: 17 },
		{ item: Items.getOrThrow('Agility potion (3)'), lvl: 26 },
		{ item: Items.getOrThrow('Agility potion (4)'), lvl: 34 },
		{ item: Items.getOrThrow('Combat potion (1)'), lvl: 9 },
		{ item: Items.getOrThrow('Combat potion (2)'), lvl: 18 },
		{ item: Items.getOrThrow('Combat potion (3)'), lvl: 27 },
		{ item: Items.getOrThrow('Combat potion (4)'), lvl: 36 },
		{ item: Items.getOrThrow('Prayer potion (1)'), lvl: 10 },
		{ item: Items.getOrThrow('Prayer potion (2)'), lvl: 19 },
		{ item: Items.getOrThrow('Prayer potion (3)'), lvl: 29 },
		{ item: Items.getOrThrow('Prayer potion (4)'), lvl: 38 },
		{ item: Items.getOrThrow('Super attack (1)'), lvl: 12 },
		{ item: Items.getOrThrow('Super attack (2)'), lvl: 23 },
		{ item: Items.getOrThrow('Super attack (3)'), lvl: 34 },
		{ item: Items.getOrThrow('Super attack (4)'), lvl: 45 },
		{ item: Items.getOrThrow('Superantipoison (1)'), lvl: 12 },
		{ item: Items.getOrThrow('Superantipoison (2)'), lvl: 24 },
		{ item: Items.getOrThrow('Superantipoison (3)'), lvl: 36 },
		{ item: Items.getOrThrow('Superantipoison (4)'), lvl: 48 },
		{ item: Items.getOrThrow('Fishing potion (1)'), lvl: 13 },
		{ item: Items.getOrThrow('Fishing potion (2)'), lvl: 25 },
		{ item: Items.getOrThrow('Fishing potion (3)'), lvl: 38 },
		{ item: Items.getOrThrow('Fishing potion (4)'), lvl: 50 },
		{ item: Items.getOrThrow('Super energy (1)'), lvl: 13 },
		{ item: Items.getOrThrow('Super energy (2)'), lvl: 26 },
		{ item: Items.getOrThrow('Super energy (3)'), lvl: 39 },
		{ item: Items.getOrThrow('Super energy (4)'), lvl: 52 },
		{ item: Items.getOrThrow('Hunter potion (1)'), lvl: 14 },
		{ item: Items.getOrThrow('Hunter potion (2)'), lvl: 27 },
		{ item: Items.getOrThrow('Hunter potion (3)'), lvl: 40 },
		{ item: Items.getOrThrow('Hunter potion (4)'), lvl: 53 },
		{ item: Items.getOrThrow('Super strength (1)'), lvl: 14 },
		{ item: Items.getOrThrow('Super strength (2)'), lvl: 28 },
		{ item: Items.getOrThrow('Super strength (3)'), lvl: 42 },
		{ item: Items.getOrThrow('Super strength (4)'), lvl: 55 },
		{ item: Items.getOrThrow('Super restore (1)'), lvl: 16 },
		{ item: Items.getOrThrow('Super restore (2)'), lvl: 32 },
		{ item: Items.getOrThrow('Super restore (3)'), lvl: 48 },
		{ item: Items.getOrThrow('Super restore (4)'), lvl: 63 },
		{ item: Items.getOrThrow('Super defence (1)'), lvl: 17 },
		{ item: Items.getOrThrow('Super defence (2)'), lvl: 33 },
		{ item: Items.getOrThrow('Super defence (3)'), lvl: 50 },
		{ item: Items.getOrThrow('Super defence (4)'), lvl: 66 },
		{ item: Items.getOrThrow('Antidote+ (1)'), lvl: 17 },
		{ item: Items.getOrThrow('Antidote+ (2)'), lvl: 34 },
		{ item: Items.getOrThrow('Antidote+ (3)'), lvl: 51 },
		{ item: Items.getOrThrow('Antidote+ (4)'), lvl: 68 },
		{ item: Items.getOrThrow('Antifire potion (1)'), lvl: 18 },
		{ item: Items.getOrThrow('Antifire potion (2)'), lvl: 35 },
		{ item: Items.getOrThrow('Antifire potion (3)'), lvl: 52 },
		{ item: Items.getOrThrow('Antifire potion (4)'), lvl: 69 },
		{ item: Items.getOrThrow('Ranging potion (1)'), lvl: 18 },
		{ item: Items.getOrThrow('Ranging potion (2)'), lvl: 36 },
		{ item: Items.getOrThrow('Ranging potion (3)'), lvl: 54 },
		{ item: Items.getOrThrow('Ranging potion (4)'), lvl: 72 },
		{ item: Items.getOrThrow('Magic potion (1)'), lvl: 19 },
		{ item: Items.getOrThrow('Magic potion (2)'), lvl: 38 },
		{ item: Items.getOrThrow('Magic potion (3)'), lvl: 57 },
		{ item: Items.getOrThrow('Magic potion (4)'), lvl: 76 },
		{ item: Items.getOrThrow('Stamina potion (1)'), lvl: 20 },
		{ item: Items.getOrThrow('Stamina potion (2)'), lvl: 39 },
		{ item: Items.getOrThrow('Stamina potion (3)'), lvl: 58 },
		{ item: Items.getOrThrow('Stamina potion (4)'), lvl: 77 },
		{ item: Items.getOrThrow('Zamorak brew (1)'), lvl: 20 },
		{ item: Items.getOrThrow('Zamorak brew (2)'), lvl: 39 },
		{ item: Items.getOrThrow('Zamorak brew (3)'), lvl: 59 },
		{ item: Items.getOrThrow('Zamorak brew (4)'), lvl: 78 },
		{ item: Items.getOrThrow('Antidote++ (1)'), lvl: 20 },
		{ item: Items.getOrThrow('Antidote++ (2)'), lvl: 40 },
		{ item: Items.getOrThrow('Antidote++ (3)'), lvl: 60 },
		{ item: Items.getOrThrow('Antidote++ (4)'), lvl: 79 },
		{ item: Items.getOrThrow('Bastion potion (1)'), lvl: 20 },
		{ item: Items.getOrThrow('Bastion potion (2)'), lvl: 40 },
		{ item: Items.getOrThrow('Bastion potion (3)'), lvl: 60 },
		{ item: Items.getOrThrow('Bastion potion (4)'), lvl: 80 },
		{ item: Items.getOrThrow('Battlemage potion (1)'), lvl: 20 },
		{ item: Items.getOrThrow('Battlemage potion (2)'), lvl: 40 },
		{ item: Items.getOrThrow('Battlemage potion (3)'), lvl: 60 },
		{ item: Items.getOrThrow('Battlemage potion (4)'), lvl: 80 },
		{ item: Items.getOrThrow('Saradomin brew (1)'), lvl: 21 },
		{ item: Items.getOrThrow('Saradomin brew (2)'), lvl: 41 },
		{ item: Items.getOrThrow('Saradomin brew (3)'), lvl: 61 },
		{ item: Items.getOrThrow('Saradomin brew (4)'), lvl: 81 },
		{ item: Items.getOrThrow('Extended antifire (1)'), lvl: 21 },
		{ item: Items.getOrThrow('Extended antifire (2)'), lvl: 42 },
		{ item: Items.getOrThrow('Extended antifire (3)'), lvl: 63 },
		{ item: Items.getOrThrow('Extended antifire (4)'), lvl: 84 },
		{ item: Items.getOrThrow('Anti-venom (1)'), lvl: 22 },
		{ item: Items.getOrThrow('Anti-venom (2)'), lvl: 44 },
		{ item: Items.getOrThrow('Anti-venom (3)'), lvl: 66 },
		{ item: Items.getOrThrow('Anti-venom (4)'), lvl: 87 },
		{ item: Items.getOrThrow('Super combat potion (1)'), lvl: 23 },
		{ item: Items.getOrThrow('Super combat potion (2)'), lvl: 45 },
		{ item: Items.getOrThrow('Super combat potion (3)'), lvl: 68 },
		{ item: Items.getOrThrow('Super combat potion (4)'), lvl: 90 },
		{ item: Items.getOrThrow('Super antifire potion (1)'), lvl: 23 },
		{ item: Items.getOrThrow('Super antifire potion (2)'), lvl: 46 },
		{ item: Items.getOrThrow('Super antifire potion (3)'), lvl: 69 },
		{ item: Items.getOrThrow('Super antifire potion (4)'), lvl: 92 },
		{ item: Items.getOrThrow('Anti-venom+ (1)'), lvl: 24 },
		{ item: Items.getOrThrow('Anti-venom+ (2)'), lvl: 47 },
		{ item: Items.getOrThrow('Anti-venom+ (3)'), lvl: 71 },
		{ item: Items.getOrThrow('Anti-venom+ (4)'), lvl: 94 },
		{ item: Items.getOrThrow('Extended super antifire (1)'), lvl: 25 },
		{ item: Items.getOrThrow('Extended super antifire (2)'), lvl: 49 },
		{ item: Items.getOrThrow('Extended super antifire (3)'), lvl: 74 },
		{ item: Items.getOrThrow('Extended super antifire (4)'), lvl: 98 },
		{ item: Items.getOrThrow('Sanfew serum (1)'), lvl: 17 },
		{ item: Items.getOrThrow('Sanfew serum (2)'), lvl: 33 },
		{ item: Items.getOrThrow('Sanfew serum (3)'), lvl: 49 },
		{ item: Items.getOrThrow('Sanfew serum (4)'), lvl: 65 },
		{ item: ['Heat res. brew', 'Heat res. restore'].map(i), lvl: 99 }
	],
	parts: { precious: 35, organic: 32, magic: 10 }
};
