import getOSItem from '../../util/getOSItem';
import { DisassemblySourceGroup } from '..';

const i = getOSItem;

export const Seed: DisassemblySourceGroup = {
	name: 'Seed',
	items: [
		{ item: i('Potato seed'), lvl: 1 },
		{ item: i('Marigold seed'), lvl: 2 },
		{ item: i('Barley seed'), lvl: 3 },
		{ item: i('Hammerstone seed'), lvl: 4 },
		{ item: i('Onion seed'), lvl: 5 },
		{ item: i('Cabbage seed'), lvl: 7 },
		{ item: i('Asgarnian seed'), lvl: 8 },
		{ item: i('Guam seed'), lvl: 9 },
		{ item: i('Delphinium seed'), lvl: 10 },
		{ item: i('Pink rose seed'), lvl: 10 },
		{ item: i('Red rose seed'), lvl: 10 },
		{ item: i('Redberry seed'), lvl: 10 },
		{ item: i('Snowdrop seed'), lvl: 10 },
		{ item: i('Vine seed'), lvl: 10 },
		{ item: i('White rose seed'), lvl: 10 },
		{ item: i('Rosemary seed'), lvl: 11 },
		{ item: i('Tomato seed'), lvl: 12 },
		{ item: i('Jute seed'), lvl: 13 },
		{ item: i('Marrentill seed'), lvl: 14 },
		{ item: i('Yanillian seed'), lvl: 16 },
		{ item: i('Kelda seed'), lvl: 17 },
		{ item: i('Tarromin seed'), lvl: 19 },
		{ item: i('Sweetcorn seed'), lvl: 20 },
		{ item: i('Krandorian seed'), lvl: 21 },
		{ item: i('Cadavaberry seed'), lvl: 22 },
		{ item: i('Nasturtium seed'), lvl: 24 },
		{ item: i('White tree shoot'), lvl: 25 },
		{ item: i('Woad seed'), lvl: 25 },
		{ item: i('Harralander seed'), lvl: 26 },
		{ item: i('Limpwurt seed'), lvl: 26 },
		{ item: i('Apple tree seed'), lvl: 27 },
		{ item: i('Wildblood seed'), lvl: 28 },
		{ item: i('Gout tuber'), lvl: 29 },
		{ item: i('Willow seed'), lvl: 30 },
		{ item: i('Strawberry seed'), lvl: 31 },
		{ item: i('Ranarr seed'), lvl: 32 },
		{ item: i('Banana tree seed'), lvl: 33 },
		{ item: i('Dwellberry seed'), lvl: 36 },
		{ item: i('Toadflax seed'), lvl: 38 },
		{ item: i('Orange tree seed'), lvl: 39 },
		{ item: i('Blindweed seed'), lvl: 40 },
		{ item: i('Curry tree seed'), lvl: 42 },
		{ item: i('Irit seed'), lvl: 44 },
		{ item: i('Maple seed'), lvl: 45 },
		{ item: i('Watermelon seed'), lvl: 47 },
		{ item: i('Jangerberry seed'), lvl: 48 },
		{ item: i('Avantoe seed'), lvl: 50 },
		{ item: i('Pineapple seed'), lvl: 51 },
		{ item: i('White lily seed'), lvl: 52 },
		{ item: i('Mahogany seed'), lvl: 55 },
		{ item: i('Cactus seed'), lvl: 55 },
		{ item: i('Kwuarm seed'), lvl: 56 },
		{ item: i('Papaya tree seed'), lvl: 57 },
		{ item: i('Whiteberry seed'), lvl: 59 },
		{ item: i('Yew seed'), lvl: 60 },
		{ item: i('Snapdragon seed'), lvl: 62 },
		{ item: i('Belladonna seed'), lvl: 63 },
		{ item: i('Cadantine seed'), lvl: 67 },
		{ item: i('Palm tree seed'), lvl: 68 },
		{ item: i('Poison ivy seed'), lvl: 70 },
		{ item: i('Calquat tree seed'), lvl: 72 },
		{ item: i('Lantadyme seed'), lvl: 73 },
		{ item: i('Magic seed'), lvl: 75 },
		{ item: i('Dwarf weed seed'), lvl: 79 },
		{ item: i('Snape grass seed'), lvl: 80 },
		{ item: i('Spirit seed'), lvl: 83 },
		{ item: i('Torstol seed'), lvl: 85 },
		{ item: i('Potato cactus seed'), lvl: 86 },
		{ item: i('Avocado seed'), lvl: 99 },
		{ item: i('Mango seed'), lvl: 105 },
		{ item: i('Lychee seed'), lvl: 111 }
	],
	parts: { organic: 99 }
};
