import getOSItem from '../../util/getOSItem';
import { DisassemblySourceGroup } from '..';

const i = getOSItem;

export const Seed: DisassemblySourceGroup = {
	name: 'Seed',
	items: [
		{ item: i('Apple sapling'), lvl: 27, partQuantity: 1 },
		{ item: i('Calquat sapling'), lvl: 72, partQuantity: 1 },
		{ item: i('Calquat seedling'), lvl: 72, partQuantity: 1 },
		{ item: i('Calquat seedling (w)'), lvl: 72, partQuantity: 1 },
		{ item: i('Potato seed'), lvl: 1, partQuantity: 1 },
		{ item: i('Marigold seed'), lvl: 2, partQuantity: 1 },
		{ item: i('Barley seed'), lvl: 3, partQuantity: 1 },
		{ item: i('Hammerstone seed'), lvl: 4, partQuantity: 1 },
		{ item: i('Onion seed'), lvl: 5, partQuantity: 1 },
		{ item: i('Cabbage seed'), lvl: 7, partQuantity: 1 },
		{ item: i('Asgarnian seed'), lvl: 8, partQuantity: 1 },
		{ item: i('Guam seed'), lvl: 9, partQuantity: 1 },
		{ item: i('Delphinium seed'), lvl: 10, partQuantity: 1 },
		{ item: i('Pink rose seed'), lvl: 10, partQuantity: 1 },
		{ item: i('Red rose seed'), lvl: 10, partQuantity: 1 },
		{ item: i('Redberry seed'), lvl: 10, partQuantity: 1 },
		{ item: i('Snowdrop seed'), lvl: 10, partQuantity: 1 },
		{ item: i('Vine seed'), lvl: 10, partQuantity: 1 },
		{ item: i('White rose seed'), lvl: 10, partQuantity: 1 },
		{ item: i('White tree sapling'), lvl: 10, partQuantity: 1 },
		{ item: i('Rosemary seed'), lvl: 11, partQuantity: 1 },
		{ item: i('Tomato seed'), lvl: 12, partQuantity: 1 },
		{ item: i('Jute seed'), lvl: 13, partQuantity: 1 },
		{ item: i('Marrentill seed'), lvl: 14, partQuantity: 1 },
		{ item: i('Oak sapling'), lvl: 15, partQuantity: 1 },
		{ item: i('Oak seedling'), lvl: 15, partQuantity: 1 },
		{ item: i('Oak seedling (w)'), lvl: 15, partQuantity: 1 },
		{ item: i('Yanillian seed'), lvl: 16, partQuantity: 1 },
		{ item: i('Kelda seed'), lvl: 17, partQuantity: 1 },
		{ item: i('Tarromin seed'), lvl: 19, partQuantity: 1 },
		{ item: i('Sweetcorn seed'), lvl: 20, partQuantity: 1 },
		{ item: i('Krandorian seed'), lvl: 21, partQuantity: 1 },
		{ item: i('Cadavaberry seed'), lvl: 22, partQuantity: 1 },
		{ item: i('Nasturtium seed'), lvl: 24, partQuantity: 1 },
		{ item: i('White tree shoot'), lvl: 25, partQuantity: 1 },
		{ item: i('Woad seed'), lvl: 25, partQuantity: 1 },
		{ item: i('Harralander seed'), lvl: 26, partQuantity: 1 },
		{ item: i('Limpwurt seed'), lvl: 26, partQuantity: 1 },
		{ item: i('Apple seedling'), lvl: 27, partQuantity: 1 },
		{ item: i('Apple seedling (w)'), lvl: 27, partQuantity: 1 },
		{ item: i('Apple tree seed'), lvl: 27, partQuantity: 1 },
		{ item: i('Wildblood seed'), lvl: 28, partQuantity: 1 },
		{ item: i('Gout tuber'), lvl: 29, partQuantity: 1 },
		{ item: i("Auguste's sapling"), lvl: 30, partQuantity: 1 },
		{ item: i('Willow sapling'), lvl: 30, partQuantity: 1 },
		{ item: i('Willow seed'), lvl: 30, partQuantity: 1 },
		{ item: i('Willow seedling'), lvl: 30, partQuantity: 1 },
		{ item: i('Willow seedling (w)'), lvl: 30, partQuantity: 1 },
		{ item: i('Strawberry seed'), lvl: 31, partQuantity: 1 },
		{ item: i('Ranarr seed'), lvl: 32, partQuantity: 1 },
		{ item: i('Banana sapling'), lvl: 33, partQuantity: 1 },
		{ item: i('Banana seedling'), lvl: 33, partQuantity: 1 },
		{ item: i('Banana seedling (w)'), lvl: 33, partQuantity: 1 },
		{ item: i('Banana tree seed'), lvl: 33, partQuantity: 1 },
		{ item: i('Dwellberry seed'), lvl: 36, partQuantity: 1 },
		{ item: i('Toadflax seed'), lvl: 38, partQuantity: 1 },
		{ item: i('Orange sapling'), lvl: 39, partQuantity: 1 },
		{ item: i('Orange seedling'), lvl: 39, partQuantity: 1 },
		{ item: i('Orange seedling (w)'), lvl: 39, partQuantity: 1 },
		{ item: i('Orange tree seed'), lvl: 39, partQuantity: 1 },
		{ item: i('Blindweed seed'), lvl: 40, partQuantity: 1 },
		{ item: i('Curry sapling'), lvl: 42, partQuantity: 1 },
		{ item: i('Curry seedling'), lvl: 42, partQuantity: 1 },
		{ item: i('Curry seedling (w)'), lvl: 42, partQuantity: 1 },
		{ item: i('Curry tree seed'), lvl: 42, partQuantity: 1 },
		{ item: i('Irit seed'), lvl: 44, partQuantity: 1 },
		{ item: i('Maple sapling'), lvl: 45, partQuantity: 1 },
		{ item: i('Maple seed'), lvl: 45, partQuantity: 1 },
		{ item: i('Maple seedling'), lvl: 45, partQuantity: 1 },
		{ item: i('Maple seedling (w)'), lvl: 45, partQuantity: 1 },
		{ item: i('Watermelon seed'), lvl: 47, partQuantity: 1 },
		{ item: i('Jangerberry seed'), lvl: 48, partQuantity: 1 },
		{ item: i('Avantoe seed'), lvl: 50, partQuantity: 1 },
		{ item: i('Pineapple sapling'), lvl: 51, partQuantity: 1 },
		{ item: i('Pineapple seed'), lvl: 51, partQuantity: 1 },
		{ item: i('Pineapple seedling'), lvl: 51, partQuantity: 1 },
		{ item: i('Pineapple seedling (w)'), lvl: 51, partQuantity: 1 },
		{ item: i('White lily seed'), lvl: 52, partQuantity: 1 },
		{ item: i('Cactus seed'), lvl: 55, partQuantity: 1 },
		{ item: i('Kwuarm seed'), lvl: 56, partQuantity: 1 },
		{ item: i('Papaya sapling'), lvl: 57, partQuantity: 1 },
		{ item: i('Papaya seedling'), lvl: 57, partQuantity: 1 },
		{ item: i('Papaya seedling (w)'), lvl: 57, partQuantity: 1 },
		{ item: i('Papaya tree seed'), lvl: 57, partQuantity: 1 },
		{ item: i('Whiteberry seed'), lvl: 59, partQuantity: 1 },
		{ item: i('Yew sapling'), lvl: 60, partQuantity: 1 },
		{ item: i('Yew seed'), lvl: 60, partQuantity: 1 },
		{ item: i('Yew seedling'), lvl: 60, partQuantity: 1 },
		{ item: i('Yew seedling (w)'), lvl: 60, partQuantity: 1 },
		{ item: i('Snapdragon seed'), lvl: 62, partQuantity: 1 },
		{ item: i('Belladonna seed'), lvl: 63, partQuantity: 1 },
		{ item: i('Cadantine seed'), lvl: 67, partQuantity: 1 },
		{ item: i('Palm sapling'), lvl: 68, partQuantity: 1 },
		{ item: i('Palm seedling'), lvl: 68, partQuantity: 1 },
		{ item: i('Palm seedling (w)'), lvl: 68, partQuantity: 1 },
		{ item: i('Palm tree seed'), lvl: 68, partQuantity: 1 },
		{ item: i('Poison ivy seed'), lvl: 70, partQuantity: 1 },
		{ item: i('Calquat tree seed'), lvl: 72, partQuantity: 1 },
		{ item: i('Lantadyme seed'), lvl: 73, partQuantity: 1 },
		{ item: i('Magic sapling'), lvl: 75, partQuantity: 1 },
		{ item: i('Magic seed'), lvl: 75, partQuantity: 1 },
		{ item: i('Magic seedling'), lvl: 75, partQuantity: 1 },
		{ item: i('Magic seedling (w)'), lvl: 75, partQuantity: 1 },
		{ item: i('Dwarf weed seed'), lvl: 79, partQuantity: 1 },
		{ item: i('Snape grass seed'), lvl: 80, partQuantity: 1 },
		{ item: i('Spirit sapling'), lvl: 83, partQuantity: 1 },
		{ item: i('Spirit seed'), lvl: 83, partQuantity: 1 },
		{ item: i('Spirit seedling'), lvl: 83, partQuantity: 1 },
		{ item: i('Spirit seedling (w)'), lvl: 83, partQuantity: 1 },
		{ item: i('Torstol seed'), lvl: 85, partQuantity: 1 },
		{ item: i('Potato cactus seed'), lvl: 86, partQuantity: 1 }
	],
	parts: { living: 1, organic: 99 }
};

export default Seed;
