import { resolveItems } from 'oldschooljs';

import { assert } from '@/lib/util/logError.js';

export const cmbClothes = resolveItems([
	'Swanky boots',
	'Darkmeyer hood',
	'Darkmeyer torso',
	'Darkmeyer trousers',
	'Darkmeyer boots',
	'Gorilla mask',
	'Thinker robes',
	'Thinker trousers',
	'Thinker gloves',
	'Thinker boots',
	"Prifddinian worker's robes",
	"Prifddinian worker's trousers",
	"Prifddinian worker's gloves",
	"Prifddinian worker's boots",
	"Prifddinian musician's robe top",
	"Prifddinian musician's robe bottom",
	"Prifddinian musician's gloves",
	"Prifddinian musician's boots",
	'Dervish head wrap (blue-gold)',
	'Dervish hood (red)',
	'Dervish robe (blue-gold)',
	'Dervish robe (red)',
	'Dervish trousers (blue-gold)',
	'Dervish skirt (red)',
	'Dervish shoes (blue-gold)',
	'Dervish shoes (red)',
	'Eastern knot',
	'Eastern bun',
	'Eastern robe (blue)',
	'Eastern kimono (blue)',
	'Eastern trousers (blue)',
	'Eastern skirt (blue)',
	'Eastern sandals (male)',
	'Eastern sandals (blue, female)',
	'Tribal ringlet (red, male)',
	'Tribal ringlet (red, female)',
	'Tribal shirt (red)',
	'Tribal top (red)',
	'Tribal trousers (red)',
	'Tribal skirt (red)',
	'Tribal shoes (red, male)',
	'Samba headdress (blue, male)',
	'Samba headdress (blue, female)',
	'Samba top (blue, male)',
	'Samba top (blue, female)',
	'Samba loincloth (blue, male)',
	'Samba loincloth (blue, female)',
	'Samba sandals (blue, male)',
	'Theatrical hat (blue)',
	'Theatrical earrings (blue)',
	'Theatrical tunic (blue, male)',
	'Theatrical tunic (blue, female)',
	'Theatrical trousers (blue)',
	'Theatrical skirt (blue)',
	'Theatrical shoes (blue, male)',
	'Theatrical shoes (blue, female)',
	"Pharaoh's nemes (green)",
	"Pharaoh's bun (green)",
	"Pharaoh's ankh (green)",
	"Pharaoh's top (green)",
	"Pharaoh's shendyt (green, male)",
	"Pharaoh's shendyt (green, female)",
	"Pharaoh's sandals (green, male)",
	"Pharaoh's sandals (green, female)",
	'Wushanko headdress (blue)',
	'Wushanko hat (blue)',
	'Wushanko top (blue)',
	'Wushanko jacket (blue)',
	'Wushanko skirt (blue)',
	'Wushanko trousers (blue)',
	'Wushanko shoes (blue, male)',
	'Wushanko shoes (blue, female)',
	'Silken turban (blue, male)',
	'Silken turban (blue, female)',
	'Silken top (blue, male)',
	'Silken top (blue, female)',
	'Silken trousers (blue)',
	'Silken skirt (blue)',
	'Silken boots (blue, male)',
	'Silken boots (blue, female)',
	"Colonist's hat (blue)",
	"Colonist's bonnet (blue)",
	"Colonist's coat (blue)",
	"Colonist's dress top (blue)",
	"Colonist's trousers (blue)",
	"Colonist's skirt (blue)",
	"Colonist's boots (blue)",
	"Colonist's shoes (blue)",
	'Feathered serpent headdress (blue, male)',
	'Feathered serpent headdress (blue, female)',
	'Feathered serpent body (blue, male)',
	'Feathered serpent body (blue, female)',
	'Feathered serpent skirt (blue, male)',
	'Feathered serpent skirt (blue, female)',
	'Feathered serpent boots (blue, female)',
	'Highland war paint (blue, male)',
	'Highland war paint (blue, female)',
	'Highland shirt (blue)',
	'Highland top (blue)',
	'Highland kilt (blue, male)',
	'Highland kilt (blue, female)',
	'Highland boots (blue, male)',
	'Highland boots (blue, female)',
	"Musketeer's hat (blue, male)",
	"Musketeer's hat (blue, female)",
	"Musketeer's tabard (blue)",
	"Musketeer's top (blue)",
	"Musketeer's trousers (blue, male)",
	"Musketeer's trousers (blue, female)",
	"Musketeer's boots (blue, male)",
	"Musketeer's boots (blue, female)",
	'Elf-style wig (black, male)',
	'Elf-style wig (black, female)',
	'Elf-style coat (black)',
	'Elf-style dress top (black)',
	'Elf-style trousers (black)',
	'Elf-style skirt (black)',
	'Elf-style boots (black)',
	'Elf-style shoes (black)',
	'Werewolf mask (red, male)',
	'Werewolf torso (red, male)',
	'Werewolf legs (red, male)',
	'Werewolf claws (red, male)',
	'Werewolf paws (red, male)',
	'Ikuchi orokami mask',
	'Kodama orokami mask',
	'Akkorokamui orokami mask',
	'Karasu orokami mask',
	'Akateko orokami mask',
	'Nue orokami mask',
	'Shinigami orokami mask',
	'Oni orokami mask',
	"Shaman's headdress",
	"Shaman's leggings",
	"Shaman's moccasins",
	"Shaman's poncho",
	"Shaman's hand wraps",
	'Fang of Mohegan',
	'Round glasses',
	'Stylish glasses',
	'Pyjama slippers',
	'Pyjama top',
	'Pyjama bottoms',
	'Tuxedo jacket',
	'Tuxedo trousers',
	'Tuxedo shoes',
	'Tuxedo gloves',
	'Tuxedo cravat',
	'Evening bolero',
	'Evening dipped skirt',
	'Evening gloves',
	'Evening boots',
	'Evening masquerade mask',
	'Black afro',
	'Brown afro',
	'Burgundy afro',
	'Dark blue afro',
	'Dark brown afro',
	'Dark green afro',
	'Dark grey afro',
	'Green afro',
	'Indigo afro',
	'Light blue afro',
	'Light brown afro',
	'Light grey afro',
	'Military grey afro',
	'Mint green afro',
	'Orange afro',
	'Peach afro',
	'Pink afro',
	'Purple afro',
	'Red afro',
	'Rainbow afro',
	'Taupe afro',
	'Turquoise afro',
	'Vermilion afro',
	'Violet afro',
	'White afro',
	'Yellow afro',
	'Red top hat',
	'Green top hat',
	'Blue top hat',
	'White top hat',
	'Pink disco top',
	'Pink disco legs',
	'Pink disco gloves',
	'Pink disco boots',
	'Green disco top',
	'Green disco legs',
	'Green disco gloves',
	'Green disco boots',
	'Blue disco top',
	'Blue disco legs',
	'Blue disco gloves',
	'Blue disco boots'
]);

assert(cmbClothes.length === new Set(cmbClothes).size, 'Should be no duplicates in CMB clothes');
