name: Automatic Rebase
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' && 
      (
        contains(github.event.comment.body, '/rebase')
      )
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.8
        with:
          autosquash: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
